# NumPy where()

np.where() is very useful in Data Analytics because it lets you create values based

2. where() with numbers

sales = np.array([120, 300, 500, 250])

result = np.where(sales > 300, sales * 2, sales)

print(result)

The logic is:

120 → not greater than 300 → keep 120
300 → not greater than 300 → keep 300
500 → greater than 300 → 500 × 2
250 → not greater than 300 → keep 250

In [6]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],   # Product A
    [300, 280, 320, 350],   # Product B
    [500, 450, 470, 520],   # Product C
    [250, 270, 260, 290]    # Product D
])

print("Task 1")
result_1 = np.where(sales > 400, "High", "Normal")
print(result_1)

print("\nTask 2")
result_2 = np.where(sales > 300, sales +100, sales)
print(result_2)

print("\nTask 3")
result_3 = np.where(sales > 400, "Excellent", "Regular")
print(result_3)

Task 1
[['Normal' 'Normal' 'Normal' 'Normal']
 ['Normal' 'Normal' 'Normal' 'Normal']
 ['High' 'High' 'High' 'High']
 ['Normal' 'Normal' 'Normal' 'Normal']]

Task 2
[[120 150 180 200]
 [300 280 420 450]
 [600 550 570 620]
 [250 270 260 290]]

Task 3
[['Regular' 'Regular' 'Regular' 'Regular']
 ['Regular' 'Regular' 'Regular' 'Regular']
 ['Excellent' 'Excellent' 'Excellent' 'Excellent']
 ['Regular' 'Regular' 'Regular' 'Regular']]
