# Lesson 1: Fancy Indexing

# Instead of slicing consecutive values, we can select any positions we want.

In [1]:
import numpy as np

numbers = np.array([10,20,30,40, 50,60])
print(numbers[[0,2,5]])

[10 30 60]


In [2]:
names = np.array([
    "John",
    "Mike",
    "Sarah",
    "David",
    "Emma"
])

print(names[[4,0,2]])

['Emma' 'John' 'Sarah']


# Lesson 2: Fancy Indexing on 2D Arrays

In [ ]:
import numpy as np

scores = np.array([
    [80,90,75],
    [60,95,88],
    [100,70,65]
])

print(scores[[0,2]])

print("\nMultiple columns")
print(scores[:, [0,2]]) 
#: means every row.
#[0,2] emans Column 1 and Column 3

[[ 80  90  75]
 [100  70  65]]

Multiple columns
[[ 80  75]
 [ 60  88]
 [100  65]]


# Lesson 3: Selecting Individual Elements

Suppose we only want

80
95
65

In [7]:
import numpy as np

scores = np.array([
    [80,90,75],
    [60,95,88],
    [100,70,65]
])

rows = [0,1,2]
cols = [0,1,2]

print(scores[rows, cols])

[80 95 65]


# Lesson 4: np.where()

One of the most useful NumPy functions.

In [ ]:
numbers = np.array([10, 25, 30, 18, 45])
print(np.where(numbers > 20))

# You can retrieve the values as well

indexes = np.where(numbers > 20)
print(numbers[indexes])

(array([1, 2, 4]),)
[25 30 45]


# Lesson 5: Replace Values Using np.where()

In [ ]:
numbers = np.array([10,25,30,18,45])

new_numbers = np.where(numbers > 20, 100, numbers)
print(new_numbers)

#Meaning

# If value > 20

# replace with 100

# otherwise keep original

[ 10 100 100  18 100]


# Lesson 6: Multiple Conditions

In [11]:
numbers = np.array([10,25,30,18,45])
print(numbers[(numbers >20) & (numbers < 40)])

[25 30]


In [39]:
# Exercise 1
import numpy as np

numbers = np.array([5,10,15,20,25,30])
print("Indexes greater than 18:")
print(np.where(numbers > 18))

print("\nValues:")
indexes = np.where(numbers > 18)
print(numbers[indexes])

# Print indexes of values greater than 18
# Print those values

Indexes greater than 18:
(array([3, 4, 5]),)

Values:
[20 25 30]


In [43]:
# Exercise 2
import numpy as np

scores = np.array([
    [85,90,78],
    [92,88,95],
    [70,65,80],
    [98,99,97]
])

print("rows 2 and 4")
print(scores[[1,3]])

print("\nColumns 1 and 3")
print(scores[:,[0,2]])

print("\nPrinting using fancy indexing")

rows = [0,1,2,3]
cols = [0,1,2,2]

print(scores[rows, cols])
# Print rows 2 and 4
# Print columns 1 and 3
# Print only:
# 85
# 88
# 80
# 97

rows 2 and 4
[[92 88 95]
 [98 99 97]]

Columns 1 and 3
[[85 78]
 [92 95]
 [70 80]
 [98 97]]

Printing using fancy indexing
[85 88 80 97]


In [46]:
#Exercise 3

import numpy as np

prices = np.array([
    120,
    450,
    180,
    700,
    250,
    90
])

print("Replace every value below 200 with 200")
new_prices = np.where(prices < 200, 200, prices)


print("\nReplace every value above 500 with 500")
new_prices = np.where(new_prices > 500, 500, new_prices)

print(new_prices)



# Replace every value below 200 with 200
# Replace every value above 500 with 500
# Print the final array


Replace every value below 200 with 200

Replace every value above 500 with 500
[200 450 200 500 250 200]


In [48]:
# Exercise 4 (Mini Challenge)

import numpy as np

sales = np.array([
    [120,450,700],
    [900,250,180],
    [550,610,90],
    [800,420,300]
])

print("Stores where Jan sales > 500")
print(sales[sales[:,0] > 500, 0])

print("\nJanuary sales of those stores")
print(sales[:,[0]])

print("\nReplace every sale below 200 with 200")
new_sales = np.where(sales <200, 200, sales)
print(new_sales)

print("\nCount how many values are above 500")
print(np.sum(sales > 500))
# Print stores where January sales > 500
# Print only the January sales of those stores
# Replace every sale below 200 with 200
# Count how many values are above 500

Stores where Jan sales > 500
[900 550 800]

January sales of those stores
[[120]
 [900]
 [550]
 [800]]

Replace every sale below 200 with 200
[[200 450 700]
 [900 250 200]
 [550 610 200]
 [800 420 300]]

Count how many values are above 500
5
