Today's goal

By the end of Day 68, you should be comfortable with:

np.where(condition)
np.where(condition, value_if_true, value_if_false)
Using np.where() with a 2D array
Understanding the result shape
Combining np.where() with comparisons

And we'll keep reinforcing your () vs [] distinction as we go.

In [ ]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print("Task 1")
result_1 = np.where(sales < 250, 0, sales)
print(result_1)

print("\nTask 2")
result_2 = np.where(sales >= 400, 1, 0)
print(result_2)

print("\nTask 3")
result_3 = np.where(sales >= 400, "High", "Normal")
print(result_3)

print("\nTask 4")
result_4 = np.where(sales > 450)
print(result_4)

print("\nBONUS")
result = np.where(sales > 300, 100, sales)
All sales greater than 300 will be replace by 100 and the rest will be unchange

Task 1
[[  0   0   0   0]
 [300 280 320 350]
 [500 450 470 520]
 [250 270 260 290]]

Task 2
[[0 0 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [0 0 0 0]]

Task 3
[['Normal' 'Normal' 'Normal' 'Normal']
 ['Normal' 'Normal' 'Normal' 'Normal']
 ['High' 'High' 'High' 'High']
 ['Normal' 'Normal' 'Normal' 'Normal']]

Task 4
(array([2, 2, 2]), array([0, 2, 3]))
