1. np.clip()

np.clip() forces values to stay within a specified range.

In [ ]:
import numpy as np

sales = np.array([100, 250, 400, 550, 700])

result = np.clip(sales, 200, 500)

print(result)

2. np.clip() with a 2D array

In [ ]:
import numpy as np
sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

result = np.clip(sales, 200, 500)

print(result)

# Notice:

# Everything below 200 became 200
# Everything above 500 became 500
# Everything between 200 and 500 stayed unchanged

[[200 200 200 200]
 [300 280 320 350]
 [500 450 470 500]
 [250 270 260 290]]


3. Why is this useful?

Imagine you have customer ages:

ages = np.array([5, 18, 25, 40, 67, 90, 120])

Maybe your analysis only accepts ages between 18 and 100.

clean_ages = np.clip(ages, 18, 100)

print(clean_ages)

Result:

[18 18 25 40 67 90 100]

This is a simple form of data cleaning.

4. Important distinction

Remember your NumPy symbols:

()

Used to call a function:

np.clip(sales, 200, 500)
[]

Used to create/access arrays and elements:

sales[0]
sales[:, 1]

So:

np.clip()

means run the clip function.

In [1]:
# Day 71 Exercise

# Use this array:

import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])
print("Task 1")
sales_1 = np.clip(sales, 150, 450)
print(sales_1)

print("\nTask 2")
sales_2 = np.clip(sales, 200, 400)
print(sales_2)

print("\nTask 3")
sales_Cleaned = np.clip(sales, 250, 350)
print(sales_Cleaned)

print("\nTask 4")
clipped = np.clip(sales, 200, 400)
original_average = sales.mean()
clipped_average = clipped.mean()

print("Original average", original_average)
print("Clipped average", clipped_average)


Task 1
[[150 150 180 200]
 [300 280 320 350]
 [450 450 450 450]
 [250 270 260 290]]

Task 2
[[200 200 200 200]
 [300 280 320 350]
 [400 400 400 400]
 [250 270 260 290]]

Task 3
[[250 250 250 250]
 [300 280 320 350]
 [350 350 350 350]
 [250 270 260 290]]

Task 4
Original average 306.875
Clipped average 295.0
