In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a)
print(b)

[1 2 3]
[4 5 6]


In [2]:
vertical = np.vstack((a,b))
print(vertical)

[[1 2 3]
 [4 5 6]]


In [3]:
horizontal = np.hstack((a,b))
print(horizontal)

[1 2 3 4 5 6]


In [6]:
column = np.column_stack((a,b))
print(column)

[[1 4]
 [2 5]
 [3 6]]


In [10]:
numbers = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(numbers)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
left, right = np.hsplit(numbers, 2)

print("Left")
print(left)

print("\nRight")
print(right)

Left
[[ 1  2]
 [ 5  6]
 [ 9 10]]

Right
[[ 3  4]
 [ 7  8]
 [11 12]]


In [11]:
top, bottom = np.vsplit(numbers, [1])

print("Top")
print(top)

print("\nBottom")
print(bottom)

Top
[[1 2 3 4]]

Bottom
[[ 5  6  7  8]
 [ 9 10 11 12]]


📝 Exercise (Do It Yourself)

Create two arrays:

A = [10, 20, 30]
B = [40, 50, 60]

Complete these tasks:

1. Stack them vertically.
2. Stack them horizontally.
3. Stack them as columns.
4. Create a 4×2 array:
[[1,2],
 [3,4],
 [5,6],
 [7,8]]

In [ ]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([40, 50, 60])

print("A:", a)
print("B:", b)

print("\nVertical Stack")
print(np.vstack((a, b)))

print("\nHorizontal Stack")
print(np.hstack((a,b)))

print("\nColumns")
print(np.column_stack((a,b)))

numbers = np.array([
    [100, 200, 300, 400],
    [500, 400, 700, 800]
])

print("\nOriginal Array")
print(numbers)

left, right = np.hsplit(numbers, 2)

print("\nFirst Half")
print(left)

print("\nSecond Half")
print(right)

top, bottom = np.vsplit(numbers, 2)

print("\nTOP 2 Rows")
print(top)

print("\nBottom 2 rows")
print(bottom)




A: [10 20 30]
B: [40 50 60]

Vertical Stack
[[10 20 30]
 [40 50 60]]

Horizontal Stack
[10 20 30 40 50 60]

Columns
[[10 40]
 [20 50]
 [30 60]]

Original Array
[[100 200 300 400]
 [500 400 700 800]]

First Half
[[100 200]
 [500 400]]

Second Half
[[300 400]
 [700 800]]

TOP 2 Rows
[[100 200 300 400]]

Bottom 2 rows
[[500 400 700 800]]
