# NUMPY np.select ()

np.where(condition, value_if_true, value_if_false)

In [8]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],   # Product A
    [300, 280, 320, 350],   # Product B
    [500, 450, 470, 520],   # Product C
    [250, 270, 260, 290]    # Product D
])


result_1 = np.select(
    [sales < 200, sales > 200],
    ["Low", "Medium"],
    default= "High"
)
print(result_1)

result_2 = np.select(
    [sales < 200, sales > 200],
    [0, 50],
    default= 100
)
print(result_2)

result_3 = np.where(sales < 300, "Below Target", "Target")
print(result_3)

[['Low' 'Low' 'Low' 'High']
 ['Medium' 'Medium' 'Medium' 'Medium']
 ['Medium' 'Medium' 'Medium' 'Medium']
 ['Medium' 'Medium' 'Medium' 'Medium']]
[[  0   0   0 100]
 [ 50  50  50  50]
 [ 50  50  50  50]
 [ 50  50  50  50]]
[['Below Target' 'Below Target' 'Below Target' 'Below Target']
 ['Target' 'Below Target' 'Target' 'Target']
 ['Target' 'Target' 'Target' 'Target']
 ['Below Target' 'Below Target' 'Below Target' 'Below Target']]
