In [1]:
import numpy as np
numbers = np.array([10,20,30,40,50])
print(numbers)

[10 20 30 40 50]


In [4]:
import numpy as np

numbers = np.array([10,20,30,40,50])

print(numbers + 5)
print(numbers -5)
print(numbers *2)
print(numbers /2)

[15 25 35 45 55]
[ 5 15 25 35 45]
[ 20  40  60  80 100]
[ 5. 10. 15. 20. 25.]


In [7]:
import numpy as np

a = np.array([1,2,3])

b = np.array([4,5,6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [9]:
numbers = np.array([2,4,6, 8])

print(numbers ** 2)
print(numbers ** 3)

[ 4 16 36 64]
[  8  64 216 512]


In [10]:
numbers = np.array([4,9,16,25])

print(np.sqrt(numbers))

[2. 3. 4. 5.]


Breaking down the numpy again


In [ ]:
import numpy as np

numbers = np.array([10,20,30,40,50])

print(numbers)

[10 20 30 40 50]


In [ ]:
marks = np.array([
    [80,90,70],
    [88,75,92],
    [95,85,90]
])
print(np.max(marks))
print(np.min(marks))

95


In [9]:
import numpy as np

sales = np.array([
    120,
    150,
    170,
    200,
    180,
    210,
    190

])

print("Sales:", sales)
print("Total Sales =", np.sum(sales))
print("Total Sales = ", np.mean(sales))
print("Total Sales = ",np.min(sales))
print("Standard Deviation =", np.std(sales))
print("Sales above 180 =", sales[sales > 180])

Sales: [120 150 170 200 180 210 190]
Total Sales = 1220
Total Sales =  174.28571428571428
Total Sales =  120
Standard Deviation = 28.713930346059687
Sales above 180 = [200 210 190]


EXERCISES


🏆 Exercise 1

Create:

temperature = np.array([30,32,31,29,28,35,36])

Print:

Average temperature
Highest temperature
Lowest temperature
Total temperature
Temperatures above 31

In [16]:
import numpy as np
temperature = np.array([30,32,31,29,28,35,36])
print("Average temperature = ", np.mean(temperature))
print("Highest temperature = ", np.max(temperature))
print("Lowest temperature = ", np.min(temperature))
print("Total temperature = ", np.sum(temperature))
print("Temperatures above 31 = ", temperature[temperature > 31])

Average temperature =  31.571428571428573
Highest temperature =  36
Lowest temperature =  28
Total temperature =  221
Temperatures above 31 =  [32 35 36]


Ready for Exercise 2?

Try solving this one without looking back:

import numpy as np

ages = np.array([18, 22, 30, 25, 40, 35, 29, 21])

Print:

Mean age
Maximum age
Minimum age
Ages above 25
Ages below 25

In [28]:
import numpy as np
ages = np.array([18, 22, 30, 25, 40, 35, 29, 21])

print("Mean age =",np.mean(ages))
print("Maximum age =",np.max(ages))
print("Minimum age =",np.min(ages))
print("Ages above 25 = ",ages [ages > 25])
print("Ages below 25 =", ages[ages < 25])

Mean age = 27.5
Maximum age = 40
Minimum age = 18
Ages above 25 =  [30 40 35 29]
Ages below 25 = [18 22 21]


Next Challenge (Exercise 3)

marks = np.array([
    [78, 82, 91],
    [65, 88, 72],
    [95, 90, 85]
])

Without using loops, print:

Highest mark
Lowest mark
Average mark
Sum of all marks
All marks greater than 85

This is your first exercise using a 2D NumPy array, which is much closer to working with real datasets.

In [32]:
import numpy as np

marks = np.array([
    [75, 82, 91],
    [65, 88, 72],
    [95, 90, 85]
])

print("Highest mark =", np.max(marks))
print("Lowest mark =", np.min(marks))
print("Average mark =", np.mean(marks))
print("Sum of all marks =", np.sum(marks))
print("Marks greater than 85 are", marks[marks > 85])

Highest mark = 95
Lowest mark = 65
Average mark = 82.55555555555556
Sum of all marks = 743
Marks greater than 85 are [91 88 95 90]
