In [1]:
import numpy as np

numbers = np.array([10,20,30,40,50])

print(numbers[[0,2,4]])

[10 30 50]


# Part 2 – Selecting Multiple Rows

In [4]:

import numpy as np
scores = np.array([
    [80,90,70],
    [60,75,85],
    [95,88,92],
    [50,65,70]
])

print(scores[[0,2]])


[[80 90 70]
 [95 88 92]]


Part 3 – Selecting Multiple Columns

In [ ]:

import numpy as np
scores = np.array([
    [80,90,70],
    [60,75,85],
    [95,88,92],
    [50,65,70]
])

print(scores[:,[0,2]])

# Meaning

# All rows

# Columns 0 and 2


[[80 70]
 [60 85]
 [95 92]
 [50 70]]


Part 4 – Reordering Rows

Fancy indexing also changes order.

In [ ]:
import numpy as np
scores = np.array([
    [80,90,70],
    [60,75,85],
    [95,88,92],
    [50,65,70]
])

print(scores[[2,0,3]])
# Notice the rows appear in the order you requested.

[[95 88 92]
 [80 90 70]
 [50 65 70]]


Part 5 – Repeating Rows

You can even repeat rows.

print(scores[[1,1,2]])

Output

[[60 75 85]
 [60 75 85]
 [95 88 92]]


In [8]:
print(scores[[1,1,2]])

[[60 75 85]
 [60 75 85]
 [95 88 92]]


In [9]:
# Part 6 – Selecting Individual Elements

# Suppose

numbers = np.array([10,20,30,40,50])
print(numbers[[4,0,3]])

[50 10 40]


Part 7 – Picking Individual Values from a Matrix
Suppose you want

10

50

90

In [ ]:
matrix = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

rows = [0,1,2]
cols = [0,1,2]

print(matrix[rows, cols])

[10 50 90]


Part 8 – Fancy Indexing vs Slicing

Slicing

In [13]:
import numpy as np
numbers = np.array([10,20,30,40,50])


print("Fancy indexing")

print(numbers[[1,4]])

print("\nSlicing Indexing")
print(numbers[1:4])

Fancy indexing
[20 50]

Slicing Indexing
[20 30 40]


numbers = np.array([10,20,30,40,50])

In [14]:
scores = np.array([
    [80,90,70],
    [60,75,85],
    [95,88,92],
    [50,65,70]
])

print(scores[scores[:, 0] > 70])

[[80 90 70]
 [95 88 92]]


# EXERCISE

In [ ]:
# Exercise 1
import numpy as np

numbers = np.array([5,10,15,20,25,30])

print("Printing 5, 15, 30 using fancy indexing")
print(numbers[[0,2,5]])

print("\nPrinting 20,10,25 in that order")
print(numbers[[3,1,4]])


Printing 5, 15, 30 using fancy indexing
[ 5 15 30]

Printing 20,10,25 in that order
[20 10 25]


In [26]:
# Exercise 2
import numpy as np

scores = np.array([
    [80,90,70],
    [60,75,85],
    [95,88,92],
    [50,65,70]
])
rows = [0,2]
print("Printing rows 0 and 2")
print(scores[rows])

column = [1,2]
print("\nPrinting columns 1 and 2")
print(scores[column])

print("\nPrinting rows in order")
print(scores[[3,1,0]])
# Print rows in order:
# 3
# 1

Printing rows 0 and 2
[[80 90 70]
 [95 88 92]]

Printing columns 1 and 2
[[60 75 85]
 [95 88 92]]

Printing rows in order
[[50 65 70]
 [60 75 85]
 [80 90 70]]


In [13]:
# Exercise 3
import numpy as np

matrix = np.array([
    [11,12,13],
    [21,22,23],
    [31,32,33]
])
rows = [0,1,2]
cols = [0,1,2]

print(matrix[rows, cols])

row = [2,0,1]
cols = [2,0,1]
print(matrix[rows, cols])

# Print:
# 11
# 22
# 33

# Then print:
# 13
# 21
# 32

[11 22 33]
[13 21 32]


In [28]:
# Exercise 4 (Mini Challenge)
import numpy as np

sales = np.array([
    [120,450,700],
    [900,250,180],
    [550,610,90],
    [800,420,300]
])
print("Printing only from stores 2 and 4")
print(sales[[1,3]])

print("\nPrint only Feb and Mar")
print(sales[:, [1,2]])

print("\nStores where Jan sales are above 500")
print(sales[sales[:,0] > 500])

print("\nCounting how many stores have jan sales above 500")
print(np.sum(sales[:,0] > 500))

print("\nAverage Jan sales for those stores")
print(np.mean(sales[sales[:,0] > 500, 0]))

# Print only stores:
# 2
# 4

# Print only February and March

# Print stores where January sales are above 500

# Count how many stores have January sales above 500

# Find the average January sales for those stores

Printing only from stores 2 and 4
[[900 250 180]
 [800 420 300]]

Print only Feb and Mar
[[450 700]
 [250 180]
 [610  90]
 [420 300]]

Stores where Jan sales are above 500
[[900 250 180]
 [550 610  90]
 [800 420 300]]

Counting how many stores have jan sales above 500
3

Average Jan sales for those stores
750.0


An easier way to read it

Break it into two steps:

In [29]:
jan_sales = sales[:,0]

high_sales = jan_sales[jan_sales > 500]

print(np.mean(high_sales))

750.0
