In [1]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)

[5 7 9]


In [2]:
import numpy as np

scores = np.array([70, 80, 90])
print(scores + 5)

[75 85 95]


In [3]:
import numpy as np

prices = np.array([100, 200, 300])

discount = 20

print(prices - discount)

[ 80 180 280]


In [4]:
import numpy as np

marks = np.array([60,70,80])
print(marks * 2)

[120 140 160]


Broadcasting with 2D Arrays

In [5]:
import numpy as np

scores = np.array([
    [70, 80, 90],
    [60,5,85],
    [95, 88, 92]
])

print(scores + 10)

[[ 80  90 100]
 [ 70  15  95]
 [105  98 102]]


Broadcasting Rows

In [6]:
import numpy as np

scores = np.array([
    [70,80,90],
    [60,75,85],
    [95,88,92]
])

bonus = np.array([5,5,5])
print(scores + bonus)

[[ 75  85  95]
 [ 65  80  90]
 [100  93  97]]


Broadcasting Different Values

In [7]:
import numpy as np

scores = np.array([
    [70,80,90],
    [60,75,85],
    [95,88,92]
])

bonus = np.array([2,5,10])
print(scores + bonus)


[[ 72  85 100]
 [ 62  80  95]
 [ 97  93 102]]


Broadcasting Down Columns

In [8]:
import numpy as np
scores = np.array([
    [70,80,90],
    [60,75,85],
    [95,88,92]
])

bonus = np.array([
    [5],
    [10],
    [15]
])
print(scores + bonus)

[[ 75  85  95]
 [ 70  85  95]
 [110 103 107]]


Understanding Shapes

In [10]:
print(scores.shape)
print(bonus.shape)

(3, 3)
(3, 1)


Imagine employee salaries.

In [11]:
import numpy as np

salary = np.array([
    [2500,2600,2700],
    [3000,3200,3100],
    [4000,4100,4200]
])

raise_amount = 200
print(salary+raise_amount)

[[2700 2800 2900]
 [3200 3400 3300]
 [4200 4300 4400]]


Mini Exercise 1
import numpy as np

numbers = np.array([5,10,15,20])

# Add 8 to every number

In [12]:
import numpy as np

numbers = np.array([5, 10, 15, 20])
print(numbers + 8)

[13 18 23 28]


Mini Exercise 2
import numpy as np

matrix = np.array([
    [10,20],
    [30,40]
])

# Multiply everything by 3

In [13]:
import numpy as np

matrix = np.array([
    [10,20],
    [30,40]
])
print(matrix *3)

[[ 30  60]
 [ 90 120]]


Mini Exercise 3
import numpy as np

scores = np.array([
    [60,70,80],
    [90,85,95],
    [50,65,75]
])

bonus = np.array([5,10,15])

# Add the bonus

In [15]:
import numpy as np

scores = np.array([
    [60,70,80],
    [90,85,95],
    [50,65,75]
])
bonus = np.array([5,10,15])
print(scores + bonus)

[[ 65  80  95]
 [ 95  95 110]
 [ 55  75  90]]


Mini Exercise 4
import numpy as np

scores = np.array([
    [60,70],
    [80,90],
    [100,110]
])

bonus = np.array([
    [10],
    [20],
    [30]
])

# Add the bonus

In [16]:
import numpy as np
scores = np.array([
    [60,70],
    [80,90],
    [100,110]
])

bonus = np.array([
    [10],
    [20],
    [30]
])

print(scores + bonus)

[[ 70  80]
 [100 110]
 [130 140]]


Mini Project – Student Score Improvement

In [17]:
import numpy as np
scores = np.array([
    [70,80,90],
    [60,75,85],
    [95,88,92]
])

bonus = np.array([5,3,2])

new_scores = scores + bonus

print("Original Scores")
print(scores)

print("\nBonus")
print(bonus)

print("\nNew Scores")
print(new_scores)

Original Scores
[[70 80 90]
 [60 75 85]
 [95 88 92]]

Bonus
[5 3 2]

New Scores
[[ 75  83  92]
 [ 65  78  87]
 [100  91  94]]
