In [ ]:
#1. Sample Dataset

import numpy as np

sales = np.array([
    [120, 450, 700],
    [900, 250, 180],
    [550, 610, 90],
    [800, 420, 300]
])

print(sales)

[[120 450 700]
 [900 250 180]
 [550 610  90]
 [800 420 300]]


# 2. Sum

Find total sales.
print(np.sum(sales))

In [2]:
import numpy as np

sales = np.array([
    [120, 450, 700],
    [900, 250, 180],
    [550, 610, 90],
    [800, 420, 300]
])

print(np.sum(sales))

5370


# Sum by Row
print(np.sum(sales, axis=1))

In [3]:
import numpy as np

sales = np.array([
    [120, 450, 700],
    [900, 250, 180],
    [550, 610, 90],
    [800, 420, 300]
])

print(np.sum(sales, axis=1))

[1270 1330 1250 1520]


In [4]:
# Sum by Column
print(np.sum(sales, axis=0))

[2370 1730 1270]


3. Mean (Average)
print(np.mean(sales))

In [5]:
print(np.mean(sales))

447.5


# Average of each Store (row)

In [7]:
print(np.mean(sales, axis= 1))

[423.33333333 443.33333333 416.66666667 506.66666667]


# Average of each Month (column)

In [8]:
import numpy as np

sales = np.array([
    [120, 450, 700],
    [900, 250, 180],
    [550, 610, 90],
    [800, 420, 300]
])

print(np.mean(sales, axis= 0))

[592.5 432.5 317.5]


In [ ]:
4. # Maximum
print(np.max(sales))

# Maximum per column

print(np.max(sales, axis=0))

5. Minimum
print(np.min(sales))

6. Count

Number of elements

print(sales.size)

In [9]:
import numpy as np

sales = np.array([
    [120, 450, 700],
    [900, 250, 180],
    [550, 610, 90],
    [800, 420, 300]
])

print(sales.size)

12


In [11]:
#ROWS

print(sales.shape[0])

#COLUMN

print(sales.shape[1])

4
3


7. Standard Deviation

Measures how spread out the data is.

print(np.std(sales))

In [12]:
import numpy as np

sales = np.array([
    [120, 450, 700],
    [900, 250, 180],
    [550, 610, 90],
    [800, 420, 300]
])

print(np.std(sales))

257.8476617436479


8. Variance
print(np.var(sales))

9. Find Position of Maximum Value
print(np.argmax(sales))
The maximum value (900) is at index 3 in the flattened array.

In [13]:
# Find maximum in each row:

print(np.argmax(sales, axis =1))

[2 0 1 0]


In [18]:
#Find maximum in each row:
import numpy as np

numbers = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Total Sum")
print(np.sum(numbers))

print("\nAverage:")
print(np.mean(numbers))

print("\nMaximum:")
print(np.max(numbers))

print("\nMinimum:")
print(np.min(numbers))

# Print:
# Total sum
# Average
# Maximum
# Minimum

Total Sum
450

Average:
50.0

Maximum:
90

Minimum:
10


In [ ]:
# EXERCISE 2
import numpy as np

scores = np.array([
    [75, 80, 90],
    [60, 70, 85],
    [95, 88, 92]
])

print("Average of each student")
print(np.mean(scores, axis= 1))

print("\nAverage of each exam")
print(np.mean(scores, axis= 0))

print("\nHighest score of each student")
print(np.max(scores, axis= 1))

print("\nLowest score of each exam")
print(np.min(scores, axis= 0 ))
# Print:
# Average of each student
# Average of each exam
# Highest score of each student
# Lowest score of each exam

Average of each student
[76.66666667 79.33333333 89.        ]

Average of each exam
[81.66666667 71.66666667 91.66666667]

Highest score of each student
[95 88 92]

Lowest score of each exam
[75 60 88]


In [ ]:
# 📝 Exercise 3

import numpy as np

sales = np.array([
    [120, 450, 700],
    [900, 250, 180],
    [550, 610, 90],
    [800, 420, 300]
])

print("Total sales:")
print(np.sum(sales))

print("\nSales for each month")
print(np.sum(sales, axis= 0))

print("\nSales for each store")
print(np.sum(sales, axis= 1))

print("\nHighest sales")
print(np.max(sales))

print("\nLowest sales")
print(np.min(sales))

print("\nAverage sales")
print(np.mean(sales))

print("\n Standard deviation")
print(np.std(sales))
# Print:
# Total sales
# Sales for each month
# Sales for each store
# Highest sale
# Lowest sale
# Average sale
# Standard deviation

Total sales:
5370

Sales for each month
[2370 1730 1270]

Sales for each store
[1270 1330 1250 1520]

Highest sales
900

Lowest sales
90

Average sales
447.5

 Standard deviation
257.8476617436479


In [32]:
# MINI CHALLENGE

import numpy as np

profits = np.array([
    [200, 350, 400],
    [500, 450, 600],
    [300, 700, 650],
    [800, 550, 900]
])

print("Total profit:")
print(np.sum(profits))

print("\nAverage profit per month")
print(np.mean(profits, axis= 0))

print("\nHighest profit for each company")
print(np.max(profits, axis= 1))

print("\nLowesh profit for each company")
print(np.min(profits, axis= 1))

print("\nCompany having highest total profit")
company_totals = np.sum(profits, axis = 1)
print(company_totals)

print("\nCompany having highest average profits")
monthly_average = np.mean(profits, axis=0)
print(monthly_average)

print("\nOverall Standard deviation")
print(np.std(profits))

# Find:
# 1. Total profit
# 2. Average profit per month
# 3. Highest profit for each company
# 4. Lowest profit for each company
# 5. Which company has the highest total profit?
# 6. Which month has the highest average profit?
# 7. Overall standard deviation

Total profit:
6400

Average profit per month
[450.  512.5 637.5]

Highest profit for each company
[400 600 700 900]

Lowesh profit for each company
[200 450 300 550]

Company having highest total profit
[ 950 1550 1650 2250]

Company having highest average profits
[450.  512.5 637.5]

Overall Standard deviation
199.30434571835661
