In [2]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers)

[10 20 30 40 50]


In [3]:
import numpy as np
numbers = np.array([10, 20, 30])

print(type(numbers))

<class 'numpy.ndarray'>


One-Dimensional Array

In [4]:
import numpy as np
numbers = np.array([5, 10, 15, 20])

print(numbers)

[ 5 10 15 20]


Two-Dimensional Array

In [5]:
import numpy as np

matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Array Dimensions

Use

.ndim

In [6]:
import numpy as np

numbers = np.array([10,20,30])
print(numbers.ndim)

1


In [7]:
# EXAMPLE

marix = np.array([
    [1,2],
    [3,4]
])

print(matrix.ndim)

2


Array Shape

Use

.shape

In [ ]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

print(matrix.shape)

# Meaning
# 2 rows
# 3 columns

(2, 3)


Array Size

In [ ]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

print(matrix.size)

# which means there are six values

6


Array Data Type

In [12]:
numbers = np.array([10, 20, 30])

print(numbers.dtype)

int64


Access Elements

In [14]:
numbers = np.array([5,10,15,20])

print(numbers[0]) #first element
print(numbers[-1]) #last element

5
20


Access Matrix Values

In [ ]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(matrix[0,1])

# Explanation

# row 0
# column 1

20


In [37]:
#Slicing

numbers = np.array([10, 20, 30, 40, 50])
print(numbers[1:4])

[20 30 40]


Today's Mini Project

Create this array:

scores = np.array([
    [80,90,75],
    [88,92,79],
    [95,85,91]
])

Print:

Number of dimensions
Shape
Size
Data type
First row
Last column
The value 92

In [50]:
import numpy as np
scores = np.array([
    [80,90, 75],
    [88, 92, 79],
    [95, 85, 91]
])


print("Number of dimension",scores.ndim)

print("Shape",scores.shape)

print("Size =", scores.size)

print("Datatype =", scores.dtype)

print("First row is", scores[0])

print("Last column is", scores[:,2])

print("The Value 92 is",scores[1,1])


Number of dimension 2
Shape (3, 3)
Size = 9
Datatype = int64
First row is [80 90 75]
Last column is [75 79 91]
The Value 92 is 92
