In [2]:
import numpy as np

numbers = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(numbers)

flat = numbers.flatten()

print("\nFlattened:")
print(flat)

[[10 20 30]
 [40 50 60]]

Flattened:
[10 20 30 40 50 60]


Flattern and ravel are the same but ravel is a bit stronger. Either way its the same


In [ ]:
import numpy as np

numbers = np.array([
    [1, 2, 3],
    [4, 5,6]
])

print(numbers.ravel())


[1 2 3 4 5 6]


3. Transpose

Rows become columns.

In [5]:
import numpy as np

numbers = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Original")
print(numbers)

print("\nTranspose")
print(numbers.T)

Original
[[10 20 30]
 [40 50 60]]

Transpose
[[10 40]
 [20 50]
 [30 60]]


4. Swap Axes

Useful for 3D arrays.

In [10]:
import numpy as np

array = np.arange(24).reshape(2,3,4)
print(array.shape)

new = array.swapaxes(0, 1)

print(new.shape)

(2, 3, 4)
(3, 2, 4)


```python
**5. Squeeze

Removes dimensions of size 1.**
```

In [12]:
array = np.array([[[10,20,30]]])
print(array.shape)

new = np.squeeze(array)

print(new.shape)
print(new)

(1, 1, 3)
(3,)
[10 20 30]


6. Expand Dimensions
Adding a new axis

In [23]:
import numpy as np

arr = np.array([10,20,30])
print(arr.shape)

new = np.expand_dims(arr, axis= 0)
print(new.shape)

print(new)

new = np.expand_dims(arr, axis=1)
print(new)

(3,)
(1, 3)
[[10 20 30]]
[[10]
 [20]
 [30]]


7. Resize an Array

In [24]:
import numpy as np

arr = np.array([1,2,3,4])

new = np.resize(arr, (2,4))
print(new)

[[1 2 3 4]
 [1 2 3 4]]


🎯 Mini Exercise

scores = np.array([
    [75, 80, 90],
    [60, 70, 85],
    [95, 88, 92]
])

Complete these tasks:

* Print the original array.
* Flatten it.
* Use ravel().
* Print the transpose.
* Print the shape.
* Convert it into a column vector using reshape(-1, 1).
* Convert it into a row vector using reshape(1, -1).
* Use expand_dims() with axis=0.
* Use expand_dims() with axis=1.
* Print the shape after every operation.

In [41]:
import numpy as np

scores = np.array([
    [75, 80, 90],
    [60, 70, 85],
    [95, 88, 92]
])

print("Original array")
print(scores)

flat = scores.flatten()
print("\nFlattened:")
print(flat)

print("\nUsing ravel()")
print(scores.ravel())

print("\nPrinting the transpose")
print(scores.T)

print("\nPrinting shape")
print(scores.shape)

print("\nConverting Column vector using reshape")
column = scores.reshape(-1,1)

print(column)
print(column.shape)

print("\nConverting Row vector using reshape")
row = scores.reshape(1, -1)

print(row)
print(row.shape)

print("\nUsing expand_dims() with axis=0.")
new = np.expand_dims(scores, axis= 0)
print(new.shape)

print("\nUsing expand_dims() with axis=1.")
new = np.expand_dims(scores, axis=1)
print(new.shape)

Original array
[[75 80 90]
 [60 70 85]
 [95 88 92]]

Flattened:
[75 80 90 60 70 85 95 88 92]

Using ravel()
[75 80 90 60 70 85 95 88 92]

Printing the transpose
[[75 60 95]
 [80 70 88]
 [90 85 92]]

Printing shape
(3, 3)

Converting Column vector using reshape
[[75]
 [80]
 [90]
 [60]
 [70]
 [85]
 [95]
 [88]
 [92]]
(9, 1)

Converting Row vector using reshape
[[75 80 90 60 70 85 95 88 92]]
(1, 9)

Using expand_dims() with axis=0.
(1, 3, 3)

Using expand_dims() with axis=1.
(3, 1, 3)
