In [1]:
import numpy as np

scores = np.array([
    [75, 82, 91],
    [60, 70, 85],
    [95, 88, 92]
])

print(scores)

[[75 82 91]
 [60 70 85]
 [95 88 92]]


2. Boolean Comparison   

In [2]:
print(scores > 80)


[[False  True  True]
 [False False  True]
 [ True  True  True]]


Use the Boolean Mask
print(scores[scores > 80])

In [3]:
import numpy as np

scores = np.array([
    [75, 82, 91],
    [60, 70, 85],
    [95, 88, 92]
])

print(scores[scores > 80])

[82 91 85 95 88 92]


4. Less Than
print(scores[scores < 80])

5. Equal To
print(scores[scores == 85])

6. Not Equal
print(scores[scores != 85])


7. Greater Than or Equal
print(scores[scores >= 90])

8. Combine Conditions (AND)

Use &

print(scores[(scores > 70) & (scores < 90)])

9. Combine Conditions (OR)

Use |

print(scores[(scores < 70) | (scores > 90)])

10. Modify Values Using Conditions

Suppose every score below 70 should become 70.

scores[scores < 70] = 70

print(scores)

In [4]:
scores[scores < 70] = 70
print(scores)

[[75 82 91]
 [70 70 85]
 [95 88 92]]


11. Count Matching Values

How many scores are above 80?

print(np.sum(scores > 80))

In [5]:
print(np.sum(scores > 80))

6


12. Find Maximum Using a Condition

In [7]:
print(np.max(scores[scores > 80]))

95


13. Find Average of Selected Values
print(np.mean(scores[scores > 80]))

In [9]:
print(np.mean(scores[scores > 80]))

88.83333333333333


EXERCISES 

In [16]:
import numpy as np
numbers = np.array([
    [10, 25, 40],
    [55, 60, 75],
    [80, 95, 100]
])

print("Numbers greater than 50")
print(numbers[numbers > 50])

print("\nNumbers less than 40")
print(numbers[numbers < 40])

print("\nNumbers between 40-90")
print(numbers[(numbers >= 40) & (numbers <=90)])

Numbers greater than 50
[ 55  60  75  80  95 100]

Numbers less than 40
[10 25]

Numbers between 40-90
[40 55 60 75 80]


In [25]:
# EXERCISE 2

import numpy as np

ages = np.array([15, 18, 20, 25, 30, 17, 16])

print("Adults 18 and above")
print(ages[ages >= 18])

print("\nThis are minors:")
print(ages [ages < 18])

print("\nThis counted adults are")
print(np.sum(ages >= 18))

print("\nAverage adults ages")
print(np.mean(ages[ages >= 18]))

Adults 18 and above
[18 20 25 30]

This are minors:
[15 17 16]

This counted adults are
4

Average adults ages
23.25


In [12]:
# 📝 Exercise 3

import numpy as np

prices = np.array([
    [120, 450, 700],
    [900, 250, 180],
    [550, 610, 90]
])

# Replace every value below 200 with 200
# Print all values above 500
# Count how many values are above 500
# Find the average of values above 500


print("\nReplacing value below 200 with 200")
prices[prices < 200] = 200
print(prices)

print("\nAll values above 500")
print(prices[prices > 500])

print("\nCounting values above 500:")
print(np.sum(prices > 500))

print("\nAverage values above 500")
print(np.mean(prices[prices > 500]))



Replacing value below 200 with 200
[[200 450 700]
 [900 250 200]
 [550 610 200]]

All values above 500
[700 900 550 610]

Counting values above 500:
4

Average values above 500
690.0


In [11]:
# Mini Challenge

# Without using loops, print only even numbers from this array:

numbers = np.array([
    [11, 24, 37],
    [48, 59, 62],
    [73, 84, 95]
])

print(numbers[numbers % 2 == 0])

[24 48 62 84]
