# NumPy Indexing & Slicing
1️⃣ Basic Indexing

Remember that NumPy uses zero-based indexing.

In [ ]:
import numpy as np

sales = np.array([100, 200, 300, 400, 500])

print(sales[0])
print(sales[2])
print(sales[-1])

In [2]:
# 2️⃣ Indexing 2D Arrays

# This is where it becomes really useful for data analysis.

import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[0]) # first row
print(sales[1]) # second row
print(sales[1, 2]) # Get value at row 2, column 3


[120 150 180 200]
[300 280 320 350]
320


3️⃣ Selecting Columns

Want the first column?

In [5]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])
print(sales[:, 0]) # first column
print(sales[:, 1]) # 2nd column



[120 300 500 250]
[150 280 450 270]


4️⃣ Slicing

Slicing lets you select a range.

In [ ]:
import numpy as np

sales = np.array([100, 200, 300, 400, 500])
print(sales[1:4]) # start at index 1, stop before index 4

[200 300 400]


# 2D slicing

In [8]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])
print(sales[:, 1:3])

[[150 180]
 [280 320]
 [450 470]
 [270 260]]


5️⃣ Boolean Indexing

You already practiced this yesterday.

In [10]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])
print(sales[sales > 300])

[320 350 500 450 470 520]


6️⃣ Combining Conditions

In [1]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])
sales[(sales > 250) & (sales < 500)]
print(sales)


[[120 150 180 200]
 [300 280 320 350]
 [500 450 470 520]
 [250 270 260 290]]


7️⃣ Fancy Indexing

In [ ]:
sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

#You want rows 0, 2 and 3.
print(sales[[0,2,3]])

#to select specific columns
print(sales[:, [0, 2]]) #Give me every row but only columns 0 and 2


[[120 150 180 200]
 [500 450 470 520]
 [250 270 260 290]]
[[120 180]
 [300 320]
 [500 470]
 [250 260]]


Day 56 — Exercise 1

In [33]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print("Printing the third row")
print(sales[2])

print("\nPrinting the second column")
print(sales[:, 1])

print("\nPrinting the value 470")
print(sales[2,2])

print("\nPrinting the first two rows")
print(sales[0:2])

print("\nPrinting the last two columns")
print(sales[:, 2:4])

print("\nprinting all values greater than 300")
print(sales[sales > 300])

print("\nprinting only rows 0 and 3 using fancy indexing")
print(sales[[0,3]])

print("\nprinting only columns 0 and 2")
print(sales[[0,2]])

Printing the third row
[500 450 470 520]

Printing the second column
[150 280 450 270]

Printing the value 470
470

Printing the first two rows
[[120 150 180 200]
 [300 280 320 350]]

Printing the last two columns
[[180 200]
 [320 350]
 [470 520]
 [260 290]]

printing all values greater than 300
[320 350 500 450 470 520]

printing only rows 0 and 3 using fancy indexing
[[120 150 180 200]
 [250 270 260 290]]

printing only columns 0 and 2
[[120 150 180 200]
 [500 450 470 520]]


# Day 56 — Exercise 2: Sales Analysis

             Q1   Q2   Q3   Q4
Product A   120  150  180  200
Product B   300  280  320  350
Product C   500  450  470  520
Product D   250  270  260  290

In [42]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])
print("Print the third row.") 
print(sales[2])

print("\n2. Print the second column.")
print(sales[:,1])

print("\n3. Print the value 470 using indexing.")
print(sales[2,2 ])

print("\n4. Print the first two rows.")
print(sales[0:2])

print("\n5. Print the last two columns.")
print(sales[:,2:4])

print("\n6. Print all sales values greater than 300.")
print(sales[sales>300])

print("\n7. Print only rows 0 and 3 using fancy indexing.")
print(sales[[0,3]])

print("\n8. Print only columns 0 and 2 using fancy indexing.")
print(sales[:,[0,2]])

Print the third row.
[500 450 470 520]

2. Print the second column.
[150 280 450 270]

3. Print the value 470 using indexing.
470

4. Print the first two rows.
[[120 150 180 200]
 [300 280 320 350]]

5. Print the last two columns.
[[180 200]
 [320 350]
 [470 520]
 [260 290]]

6. Print all sales values greater than 300.
[320 350 500 450 470 520]

7. Print only rows 0 and 3 using fancy indexing.
[[120 150 180 200]
 [250 270 260 290]]

8. Print only columns 0 and 2 using fancy indexing.
[[120 180]
 [300 320]
 [500 470]
 [250 260]]
