1️⃣ .reshape()

reshape() changes the shape of an array.

In [1]:
import numpy as np

sales = np.array([100, 200, 300, 400, 500, 600])

print(sales.reshape(2, 3))

[[100 200 300]
 [400 500 600]]


2. Reshaping a 2D array

In [2]:
sales = np.array([
    [100, 200, 300],
    [400, 500, 600]
])

print(sales.reshape(3, 2))

[[100 200]
 [300 400]
 [500 600]]


3. .flatten()
flatten() converts a multidimensional array into one dimension

In [3]:
sales = np.array([
    [100, 200, 300],
    [400, 500, 600]
])

print(sales.flatten())

[100 200 300 400 500 600]


4. .ravel()
ravel() also converts an array into one dimension

In [4]:
sales = np.array([
    [100, 200, 300],
    [400, 500, 600]
])

print(sales.ravel())

[100 200 300 400 500 600]


5️⃣ Transpose .T

This is very important for data analytics.

Transpose switches:

rows ↔ columns

In [5]:
sales = np.array([
    [100, 200, 300],
    [400, 500, 600]
])

print(sales.T)

[[100 400]
 [200 500]
 [300 600]]


In [ ]:
# 📝 Exercise  — Reshape


import numpy as np

sales = np.array([100, 200, 300, 400, 500, 600])

print("Original array:")
print(sales)

print("\nReshaped into 2 rows and 3 columns:")
print(sales.reshape(2,3))

Original array:
[100 200 300 400 500 600]

Reshaped into 2 rows and 3 columns:
[[100 200 300]
 [400 500 600]]


In [10]:
# 📝 Exercise 5 — Mini Challenge

profits = np.array([
    [1200, 1500, 1800],
    [2200, 2400, 2600],
    [900, 1100, 1300]
])

print(profits.reshape(1,9))

print(profits.flatten())

print(profits.T)

# Task 1

# Reshape it into 1 row and 9 columns.

# Task 2

# Flatten it back into 1D.

# Task 3

# Transpose the original array.

[[1200 1500 1800 2200 2400 2600  900 1100 1300]]
[1200 1500 1800 2200 2400 2600  900 1100 1300]
[[1200 2200  900]
 [1500 2400 1100]
 [1800 2600 1300]]
