# NumPy: Advanced Indexing & Practical Data Analysis

🎯 Today's goals


Selecting multiple specific rows
Selecting multiple specific columns
Selecting specific cells
Combining row/column indexing
Using Boolean conditions to extract useful data
A small practical sales-analysis exercise

1. Selecting multiple rows

print(sales[2])

In [1]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[[0,2]])

[[120 150 180 200]
 [500 450 470 520]]


# 2. Selecting multiple columns

In [2]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[:, 1])

[150 280 450 270]


# You can select multiple columns:

In [3]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[:, [0,2]])

[[120 180]
 [300 320]
 [500 470]
 [250 260]]


# 3. Selecting specific cells

You can select individual cells:

In [4]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[2,2])

470


# But what if you want several specific cells?

For example:

row 0, column 1 → 150
row 1, column 3 → 350
row 3, column 0 → 250

In [5]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

rows = [0, 1, 3]
cols = [1, 3, 0]

print(sales[rows, cols])

[150 350 250]


# Your Day 58 Exercise

In [18]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print("Row 1 and row 3")
print(sales[0:2])

print("\nPrinting column 1 and column 3")
print(sales[:,[0,2]])

print("\nPrinting specific values using adv indexing")
rows = [0,2,3]
cols = [2,1,3]
print(sales[rows, cols])

print("\nAll sales values greater than 400")
print(sales[sales > 400])

print("\nAll values that are greater than 250 AND less than 500")
print(sales[(sales > 250) & (sales < 500)])


Row 1 and row 3
[[120 150 180 200]
 [300 280 320 350]]

Printing column 1 and column 3
[[120 180]
 [300 320]
 [500 470]
 [250 260]]

Printing specific values using adv indexing
[180 450 290]

All sales values greater than 400
[500 450 470 520]

All values that are greater than 250 AND less than 500
[300 280 320 350 450 470 270 260 290]


# Next: Sales Analysis Challenge 🚀

In [28]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],   # Product A
    [300, 280, 320, 350],   # Product B
    [500, 450, 470, 520],   # Product C
    [250, 270, 260, 290]    # Product D
])

products = ["Product A", "Product B", "Product C", "Product D"]
months = ["January", "February", "March", "April"]

print("All sales for Product C")
print(sales[2])

print("\nSales from Jan and April for every product")
print(sales[:,[0,3]])

print("\nAll sales values greater than 400")
high_sells = (sales[sales > 400])
print(len(high_sells))

print("\nSales between 250 and 400")
print(sales[(sales >= 250) & (sales <= 400)])

print("\nSpecific cells using advance index")
rows = [0,1,2,3]
cols = [2,3,1,0]
print(sales[rows, cols])

print("\nValues greater than 300 AND less than 500")
print(sales[(sales > 300) & (sales < 500)])


All sales for Product C
[500 450 470 520]

Sales from Jan and April for every product
[[120 200]
 [300 350]
 [500 520]
 [250 290]]

All sales values greater than 400
4

Sales between 250 and 400
[300 280 320 350 250 270 260 290]

Specific cells using advance index
[180 350 450 250]

Values greater than 300 AND less than 500
[320 350 450 470]
