Exercise 2: axis with mean(), max(), and min()

You already understand:

axis=0 → calculate down each column
axis=1 → calculate across each row

Now we're going to use the same concept with other NumPy functions.

Use this array:

In [ ]:
# 📝 Exercise 2

import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print("Average sales for each store")
print(np.mean(sales, axis=1))

print("\nAverage sales for each month")
print(np.mean(sales, axis= 0))

print("\nHighest sales for each store")
print(np.max(sales, axis= 1))

print("\nLowest sale for each store")
print(np.min(sales, axis= 1))

print("\nHighest sale for each month")
print(np.max(sales, axis= 0))

print("\nLowest sale for each month")
print(np.min(sales, axis= 0))
# Task 1

# Find the average sales for each store.

# Task 2

# Find the average sales for each month.

# Task 3

# Find the highest sale for each store.

# Task 4

# Find the lowest sale for each store.

# Task 5 ⭐

# Find the highest sale for each month.

# Task 6 ⭐

# Find the lowest sale for each month.

Average sales for each store
[162.5 312.5 485.  267.5]

Average sales for each month
[292.5 287.5 307.5 340. ]

Highest sales for each month
[500 450 470 520]

Lowest sale for each store
[120 280 450 250]

Highest sale for each month
[500 450 470 520]

Lowest sale for each month
[120 150 180 200]


Exercise 3: Mini Data Analyst Challenge



In [ ]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],   # Store 1
    [300, 280, 320, 350],   # Store 2
    [500, 450, 470, 520],   # Store 3
    [250, 270, 260, 290]    # Store 4
])


# Average for each store
print("Average for each store:")
print(np.mean(sales, axis=1))


# Highest sale for each store
print("\nHighest sale for each store:")
print(np.max(sales, axis=1))


# Best performing store
store_totals = np.sum(sales, axis=1)
best_store = np.argmax(store_totals)

print("\nBest performing store:")
print("Store:", best_store + 1)
print("Total:", store_totals[best_store])


# Total for each month
month_totals = np.sum(sales, axis=0)

print("\nTotal for each month:")
print(month_totals)


# Best month
best_month = np.argmax(month_totals)

print("\nBest month:")
print("Month:", best_month + 1)


# Best month's total
best_month_total = month_totals[best_month]

print("\nBest month's total:")
print(best_month_total)

Average for each store:
[162.5 312.5 485.  267.5]

Highest sale for each store:
[200 350 520 290]

Best performing store:
Store: 3
Total: 1940

Total for each month:
[1170 1150 1230 1360]

Best month:
Month: 4

Best month's total:
1360



# Exercise 5: Combining sum() + mean() + max() + min()
This time, no new functions. We're going to practice choosing the correct function and axis.

In [ ]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],   # Store 1
    [300, 280, 320, 350],   # Store 2
    [500, 450, 470, 520],   # Store 3
    [250, 270, 260, 290]    # Store 4
])

print("Total sales for each store")
print(np.sum(sales, axis= 1))

print("\nAverage sales for each month")
print(np.mean(sales, axis= 0))

print("\nHighest sales across all stores for each month")
print(np.max(sales, axis= 0))

print("\nLowest sale across all stores for each store")
print(np.min(sales, axis= 1))

print("\nBest Peforming store")
local_stores = np.sum(sales, axis= 1)
best_stores = np.argmax(local_stores)
print(best_stores + 1)

print("\nWorst performing Month")
month_total = np.sum(sales, axis= 0)
worst_store = np.argmin(month_total)
print(worst_store + 1)


Total sales for each store
[ 650 1250 1940 1070]

Average sales for each month
[292.5 287.5 307.5 340. ]

Highest sales across all stores for each month
[500 450 470 520]

Lowest sale across all stores for each store
[120 280 450 250]

Best Peforming store
3

Worst performing Month
2


Final Mini Challenge

In [18]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],   # Store 1
    [300, 280, 320, 350],   # Store 2
    [500, 450, 470, 520],   # Store 3
    [250, 270, 260, 290]    # Store 4
])

print("Total sales for each store")
print(np.sum(sales, axis= 1))

print("\nAverage sales for each store")
print(np.mean(sales, axis= 1))

print("\nHighest sale for each month")
print(np.max(sales, axis= 0))

print("\nLowest sale for each month")
print(np.min(sales, axis= 0))

print("\nBest peforming store")
Total_stores = np.sum(sales, axis= 1)
best_store = np.argmax(Total_stores)
print(best_store + 1)

print("\nWorst performing store")
Total_stores = np.sum(sales, axis= 1)
worst_store = np.argmin(Total_stores)
print(worst_store + 1)

print("\nBest performing month")
Total_month = np.sum(sales, axis= 0)
best_month = np.argmax(Total_month)
print(best_month + 1)

print("\nWorst performing month")
Total_month = np.sum(sales, axis = 0)
worst_month = np.argmin(Total_month)
print(worst_month + 1)

Total sales for each store
[ 650 1250 1940 1070]

Average sales for each store
[162.5 312.5 485.  267.5]

Highest sale for each month
[500 450 470 520]

Lowest sale for each month
[120 150 180 200]

Best peforming store
3

Worst performing store
1

Best performing month
4

Worst performing month
2
