Today's goal

Move from basic boolean filtering into advanced indexing and selecting rows/columns based on conditions.

In [ ]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])



# 1. Selecting specific rows with an index list

sales [2] 

This means get the third row.

In [1]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[2]) #selecting specific rows with index list
print(sales[[0, 2]]) #Selecting multiple specific rows


[500 450 470 520]
[[120 150 180 200]
 [500 450 470 520]]


# 2. Selecting specific columns

You can also select specific columns using an index array.

In [ ]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[:, [1,3]]) #selecting columns 1 and 3:


[[150 200]
 [280 350]
 [450 520]
 [270 290]]


# 3. Combining row and column selection

This is where advanced indexing becomes really useful.

Suppose you want:

rows 0 and 2
columns 1 and 3

In [ ]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[[0,2], [1, 3]])
#This does not give you the 2×2 table you might expect.



[150 520]


4. Boolean filtering
sales[(sales > 250) & (sales < 500)]

# 5 — np.ix_() for selecting specific rows AND columns

sales[np.ix_([1, 2], [0, 3])]

In [32]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[np.ix_([1, 2], [0, 3])])



[[300 350]
 [500 520]]


Think of np.ix_() like this:
np.ix_(rows, columns)

It creates all combinations:

         Col 0    Col 3
Row 1     300      350
Row 2     500      520

# 6 — .any(axis=1)

Now let's learn something very useful for analyzing rows.
[[False False False False]
 [False False False False]
 [False False False  True]
 [False False False False]]

 But what if we want to ask:

Does each row contain at least one True?
That's what .any() does.



In [34]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[(sales > 500).any(axis=1)])



[[500 450 470 520]]


# 7. .all()

means:

Are ALL of them True?
[False, True, False].any()

[False, True, False].all()



In [35]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[(sales > 500).all(axis=1)])



[]


In [31]:
# Day 59 Exercise
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print("Rows 0 and 3")
print(sales[[0,3]])

print("\nColumns 0 and 2")
print(sales[:,[0,2]])

print("\nRows 1 and 2, but only columns 0 and 3")
print(sales[[1,2],[0,3]])

print("\nSales values greater than 250 AND less than 500")
print(sales[(sales > 250) & (sales < 500)])

print("\nBonus challenge finding rows containing at least one sale greater than 500")
highest_sales = sales[sales > 500]
print(np.max(highest_sales, axis= 0))


Rows 0 and 3
[[120 150 180 200]
 [250 270 260 290]]

Columns 0 and 2
[[120 180]
 [300 320]
 [500 470]
 [250 260]]

Rows 1 and 2, but only columns 0 and 3
[300 520]

Sales values greater than 250 AND less than 500
[300 280 320 350 450 470 270 260 290]

Bonus challenge finding rows containing at least one sale greater than 500
520
