1️⃣ Basic Indexing

Let's start with a simple array:

In [1]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[0, 0])

120


2️⃣ Selecting an Entire Row

In [3]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[0])
print(sales[2])

[120 150 180 200]
[500 450 470 520]


3️⃣ Selecting a Column

In [5]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[:, 0]) #:  → every row

[120 300 500 250]


4️⃣ Slicing

You can select multiple rows or columns.

First two rows

In [ ]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[0:2]) #mean Start at 0, stop before 2.

[[120 150 180 200]
 [300 280 320 350]]


5️⃣ Boolean Conditions

Now things get interesting.

In [7]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales > 300)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]
 [False False False False]]


6️⃣ Boolean Masking ⭐

In [2]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[sales > 300])

[320 350 500 450 470 520]


7️⃣ Another Example

Find all sales greater than 400:

In [3]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[sales > 400])

[500 450 470 520]


8️⃣ Filtering With <

Find all sales below 200:

In [4]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[sales < 200])

[120 150 180]


9️⃣ Filtering With >=

Find sales of at least 300:

In [5]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[sales >= 300])

[300 320 350 500 450 470 520]


🔟 Combining Conditions

You can combine conditions using:

In [6]:
# Values between 200 and 400

print(sales[(sales >= 200) & (sales <= 400)])

[200 300 280 320 350 250 270 260 290]


# Day 55 Mini Challenge

In [ ]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print("printing only third row")
print(sales[2])

print("\nprinting the second column")
print(sales[:, 1])

print("\nAll values less than or equal to 250")
print(sales[sales <= 250])

print("\nAll values between 250 and 500 including 250 and 500")
print(sales[(sales >= 250) & (sales <= 500)])

print("\nValues greater than 300")
print(len(sales[sales > 300]))

print("\nReplacing every value greater than 400 with 999")
sales[sales > 400] = 999

print(sales)

printing only third row
[500 450 470 520]

printing the second column
[150 280 450 270]

All values less than or equal to 250
[300 280 320 350 500 450 470 520 250 270 260 290]

All values between 250 and 500 including 250 and 500
[300 280 320 350 500 450 470 250 270 260 290]

Values greater than 300
6

Replacing every value greater than 400 with 999
[[120 150 180 200]
 [300 280 320 350]
 [999 999 999 999]
 [250 270 260 290]]


Day 55 — Final Challenge

In [57]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print("Greater than 250 AND less than 500")
print(sales[(sales > 250) & (sales < 500)])

print("\nHow many values satisfy that condition")
print(len(sales[(sales > 250) & (sales < 500)]))

print("\nReplace every value below 200 with 0")
sales[sales < 200] = 0
print(sales)

print("\nPrinting third row and replacing every value in that row that is greater than 480 with 1000")
sales[2][sales[2] > 480] = 1000
print(sales)

print("\nCombine challenge")
sales[sales >= 500] = 1000
sales[sales < 200] = 0
print(sales)



Greater than 250 AND less than 500
[300 280 320 350 450 470 270 260 290]

How many values satisfy that condition
9

Replace every value below 200 with 0
[[  0   0   0 200]
 [300 280 320 350]
 [500 450 470 520]
 [250 270 260 290]]

Printing third row and replacing every value in that row that is greater than 480 with 1000
[[   0    0    0  200]
 [ 300  280  320  350]
 [1000  450  470 1000]
 [ 250  270  260  290]]

Combine challenge
[[   0    0    0  200]
 [ 300  280  320  350]
 [1000  450  470 1000]
 [ 250  270  260  290]]
