
# 1. Basic Indexing

In [2]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[0,0])

120


# 2. Slicing

Slicing lets you select multiple values.

In [3]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[0:2])

[[120 150 180 200]
 [300 280 320 350]]


Selecting specific rows and columns

In [6]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])
print(sales[1:3, 0:2])

[[300 280]
 [500 450]]


3. Slicing with :

A colon by itself means everything.

In [ ]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])
print(sales[:, 1])
print(sales[2, :]) #meaning Row 2, all columns.

[150 280 450 270]
[500 450 470 520]


# 4. Boolean Indexing 
You can ask NumPy:

"Give me only the values that satisfy this condition."



In [9]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[sales > 400])

[500 450 470 520]


# Multiple conditions

In [ ]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[(sales > 250) & (sales < 500)])
#Give me values greater than 250 AND less than 500.

[300 280 320 350 450 470 270 260 290]


# 5. Fancy Indexing

Fancy indexing means selecting specific rows or columns using an array/list of indexes.

In [13]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print(sales[[0, 2]])
print(sales[:, [0, 2]]) #You can also select columns:

[[120 150 180 200]
 [500 450 470 520]]
[[120 180]
 [300 320]
 [500 470]
 [250 260]]


# Day 57 Exercise — Part 1

In [52]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])
print("Print the value 470")
print(sales[2,2])

print("\nPrinting entire second row")
print(sales[1])

print("\nPrinting the first three rows")
print(sales[0:3])

print("\nPrinting the last two columns")
print(sales[:, [2,3]])

print("\nAll values greater than 300")
print(sales[sales > 300])

print("\nAll values between 200 and 400")
print(sales[(sales > 200) & (sales < 400)])

print("\nPrinting only rows 1 and 3")
print(sales[[1,3]])

print("\nprinting only columns 0 and 3")
print(sales[:,[0,3]])

print("\nBonus challenge")
new_sales = (sales[:,[2,3]])
print(new_sales[new_sales > 250])

Print the value 470
470

Printing entire second row
[300 280 320 350]

Printing the first three rows
[[120 150 180 200]
 [300 280 320 350]
 [500 450 470 520]]

Printing the last two columns
[[180 200]
 [320 350]
 [470 520]
 [260 290]]

All values greater than 300
[320 350 500 450 470 520]

All values between 200 and 400
[300 280 320 350 250 270 260 290]

Printing only rows 1 and 3
[[300 280 320 350]
 [250 270 260 290]]

printing only columns 0 and 3
[[120 200]
 [300 350]
 [500 520]
 [250 290]]

Bonus challenge
[320 350 470 520 260 290]
