1. Median

The median is the middle value after sorting.

In [1]:
import numpy as np

numbers = np.array([4, 9, 2, 10, 100])

print(np.median(numbers))

9.0


2. Standard Deviation

Standard deviation tells us how spread out the data is.

Small standard deviation

→ Numbers are close together.

Large standard deviation

→ Numbers are spread apart.

In [2]:
import numpy as np

scores = np.array([70,72,74,76,78])

print(np.std(scores))

2.8284271247461903


# 3. Variance

Variance is similar to standard deviation.

In [3]:
import numpy as np

scores = np.array([70,72,74,76,78])

print(np.var(scores))

8.0


4. Count

Count how many values exist.

In [4]:
import numpy as np

scores = np.array([70,72,74,76,78])

print(scores.size)

5


# 5. Shape

Means

2 rows
3 columns

In [ ]:
import numpy as np

sales = np.array([
    [100,200,300],
    [400,500,600]
])

print(sales.shape)


6. Number of Dimensions
print(sales.ndim)

In [5]:
import numpy as np

sales = np.array([
    [100,200,300],
    [400,500,600]
])

print(sales.ndim)


2


7. Total Number of Elements

print(sales.size)

In [6]:
import numpy as np

sales = np.array([
    [100,200,300],
    [400,500,600]
])

print(sales.size)


6


8. Statistics Per Row

In [7]:
sales = np.array([
    [120,300,500],
    [600,400,200],
    [800,700,900]
])

print(np.mean(sales, axis=1))

[306.66666667 400.         800.        ]


9. Statistics Per Column
print(np.mean(sales, axis = 0))


In [8]:
sales = np.array([
    [120,300,500],
    [600,400,200],
    [800,700,900]
])

print(np.mean(sales, axis=0))

[506.66666667 466.66666667 533.33333333]


In [12]:
# EXERCISE 1

import numpy as np

numbers = np.array([15,20,18,30,27,25])
print("The average:")
print(np.mean(numbers))

print("\nThe standard deviation:")
print(np.std(numbers))

print("\nThe vairance")
print(np.var(numbers))

print("\nNumber of elements")
print(numbers.size)

# Print the median
# Print the standard deviation
# Print the variance
# Print the number of elements

The average:
22.5

The standard deviation:
5.251983752196243

The vairance
27.583333333333332

Number of elements
6


In [21]:
# Exercise 2

import numpy as np

profits = np.array([
    [1200,1400,1500],
    [1800,1700,1600],
    [2200,2400,2300]
])
print("Average profit of each company")
print(np.mean(profits, axis= 1))

print("\nMedian profit of each company")
print(np.median(profits, axis= 1))

print("\nhighest profit of each company")
print(np.max(profits, axis = 1))

print("\nlowest profit of each company")
print(np.min(profits, axis= 1))
# Print average profit of each company
# Print median profit of each company
# Print highest profit of each company
# Print lowest profit of each company

Average profit of each company
[1366.66666667 1700.         2300.        ]

Median profit of each company
[1400. 1700. 2300.]

highest profit of each company
[1500 1800 2400]

lowest profit of each company
[1200 1600 2200]


In [27]:
# EXERCISE 3

import numpy as np

temperatures = np.array([
    [30,32,31,33],
    [28,29,27,30],
    [35,34,36,37]
])
print("Average temperature each city:")
print(np.mean(temperatures, axis= 1))

print("\nStandard Deviation each city:")
print(np.std(temperatures, axis= 1))

print("\nMaximum temperature each city")
print(np.max(temperatures, axis= 1))

print("\nMinimum temperature each city")
print(np.min(temperatures, axis= 1))


# Average temperature each city
# Standard deviation each city
# Maximum temperature each city
# Minimum temperature each city

Average temperature each city:
[31.5 28.5 35.5]

Standard Deviation each city:
[1.11803399 1.11803399 1.11803399]

Maximum temperature each city
[33 30 37]

Minimum temperature each city
[30 27 34]


In [36]:
import numpy as np

sales = np.array([
    [120,150,180,200],
    [300,280,320,350],
    [500,450,470,520],
    [250,270,260,290]
])

print("Average sales for each store")
print(np.mean(sales, axis= 1))

print("\nMedian sales for each store")
print(np.median(sales, axis= 1))

print("\nHighest sales for each store")
print(np.max(sales, axis= 1))

print("\nLowest sales for each store")
print(np.min(sales, axis= 1))

print("\nStandard deviation for each store")
print(np.std(sales, axis= 1))

print("\nThis store has the highest average sales")
average_sales = np.mean(sales, axis= 1)
highest_store = np.argmax(average_sales)
print(highest_store)

# 1. Print average sales for each store.
# 2. Print median sales for each store.
# 3. Print the highest sales for each store.
# 4. Print the lowest sales for each store.
# 5. Print the standard deviation for each store.
# 6. Which store has the highest average sales?

Average sales for each store
[162.5 312.5 485.  267.5]

Median sales for each store
[165. 310. 485. 265.]

Highest sales for each store
[200 350 520 290]

Lowest sales for each store
[120 280 450 250]

Standard deviation for each store
[30.31088913 25.86020108 26.92582404 14.79019946]

This store has the highest average sales
2
