In [ ]:
# 1️⃣ np.concatenate()

# Used to join arrays together.

# 1D example


import numpy as np

a = np.array([10, 20, 30])
b = np.array([40, 50, 60])

result = np.concatenate((a, b))

print(result)

[10 20 30 40 50 60]


2️⃣ Concatenating 2D arrays

In [ ]:
a = np.array([
    [10, 20],
    [30, 40]
])

b = np.array([
    [50, 60],
    [70, 80]
])

In [2]:
# Join rows

result = np.concatenate((a, b), axis=0)

print(result)

[10 20 30 40 50 60]


# Join columns
result = np.concatenate((a, b), axis=1)

print(result)

In [5]:
# Join columns
a = np.array([
    [10, 20],
    [30, 40]
])

b = np.array([
    [50, 60],
    [70, 80]
])

result = np.concatenate((a, b), axis=1)

print(result)

[[10 20 50 60]
 [30 40 70 80]]


3️⃣ np.vstack()

In [6]:
a = np.array([10, 20, 30])
b = np.array([40, 50, 60])

result = np.vstack((a, b))

print(result)

[[10 20 30]
 [40 50 60]]


4️⃣ np.hstack()

hstack means horizontal stack.

In [7]:
a = np.array([10, 20, 30])
b = np.array([40, 50, 60])

result = np.hstack((a, b))

print(result)

[10 20 30 40 50 60]


5️⃣ np.split()

This does the opposite of combining.

It breaks an array into smaller arrays.

In [10]:
numbers = np.array([10, 20, 30, 40, 50, 60])

result = np.split(numbers, 3)

print(result)

#We split 6 numbers into 3 equal parts.

[array([10, 20]), array([30, 40]), array([50, 60])]


In [19]:
# 🧠 Your First Exercise

import numpy as np

sales_january = np.array([120, 150, 180])
sales_february = np.array([200, 220, 250])

total_sales = np.concatenate((sales_january, sales_february))
print("Combine January and Februaty into one array")
print(total_sales)

print("\nStack January and February vertically")
total_sales = np.vstack((sales_january, sales_february))
print(total_sales)

print("\nStack January and February horizonatally")
total_sales = np.hstack((sales_january, sales_february))
print(total_sales)

print("\nSplit the combined sales array into 2 equal parts")
split_sales = np.split(total_sales,2)
print(total_sales)
# Task 1
# Combine January and February into one array


# Task 2
# Stack January and February vertically


# Task 3
# Stack January and February horizontally


# Task 4
# Split the combined sales array into 2 equal parts

Combine January and Februaty into one array
[120 150 180 200 220 250]

Stack January and February vertically
[[120 150 180]
 [200 220 250]]

Stack January and February horizonatally
[120 150 180 200 220 250]

Split the combined sales array into 2 equal parts
[120 150 180 200 220 250]
