In [1]:
import numpy as np

a = np.array([10,20,30])
b = np.array([2,4,6])

print("Addition")
print(a + b)

print("\nSubtraction")
print(a - b)

print("\nMultiplication")
print(a * b)

print("\nDivision")
print(a / b)

Addition
[12 24 36]

Subtraction
[ 8 16 24]

Multiplication
[ 20  80 180]

Division
[5. 5. 5.]


2. Power

In [2]:
numbers = np.array([2,3,4,5])

print(numbers ** 2)
print(np.power(numbers,3))

[ 4  9 16 25]
[  8  27  64 125]


3. Square Root

In [2]:
numbers = np.array([4,9,16,25,36])

print(np.sqrt(numbers))

[2. 3. 4. 5. 6.]


# 4. Absolute Value

In [3]:
numbers = np.array([-5,-10,15,-20])
print(np.abs(numbers))

[ 5 10 15 20]


# 5. Exponential



In [4]:
numbers = np.array([1,2,3])
print(np.exp(numbers))

[ 2.71828183  7.3890561  20.08553692]


# 6. Logarithm

Suppose:

10² = 100

We know the answer is 100.

A logarithm asks the reverse question:

"10 needs to be raised to what power to become 100?"

Answer:

2

In [5]:
numbers = np.array([1,10,100,1000])

print(np.log10(numbers))

[0. 1. 2. 3.]


# 7. Rounding Numbers
# np.round(numbers, 2)

means:

Round every number in numbers to 2 decimal places.

np.round(3.14159, 2)

→ 3.14

np.round(3.14159, 3)

→ 3.142

np.round(3.14159, 1)

→ 3.1

# B. np.floor()

floor means:

Always round DOWN to the nearest whole number.

# C. np.ceil()

ceil is the opposite.
numbers = np.array([3.1, 2.2, 9.01])

print(np.ceil(numbers))

Output:

[ 4.  3. 10.]

In [6]:
numbers = np.array([3.14159,2.71828,9.87654])

print(np.round(numbers,2))

print(np.floor(numbers))

print(np.ceil(numbers))

[3.14 2.72 9.88]
[3. 2. 9.]
[ 4.  3. 10.]


In [11]:
#EXERCISES

import numpy as np
numbers = np.array([5,10,15,20])

print("Printing numbers squared:")
print(numbers ** 2)

print("\nSquare roots:")
print(np.sqrt(numbers) )

print("\nNumbers divided by 5")
print(numbers / 5)

print("\nNumbers multiplied by 3:")
print(numbers * 3)

# Print numbers squared
# Print square roots
# Print numbers divided by 5
# Print numbers multiplied by 3

Printing numbers squared:
[ 25 100 225 400]

Square roots:
[2.23606798 3.16227766 3.87298335 4.47213595]

Numbers divided by 5
[1. 2. 3. 4.]

Numbers multiplied by 3:
[15 30 45 60]


In [ ]:
# Exercise 2 — Prices

import numpy as np

prices = np.array([12.99, 45.50, 9.99, 100.75, 55.30])

print("Round to 1 decimal")
print(np.round(prices))

print("\nRound up:")
print(np.ceil(prices))

print("\nRound Down:")
print(np.floor(prices))

print("\nCalculate a 15% discount")
discount = prices * 0.15
discounted_prices = prices - discount
print(discounted_prices)

# Round to 1 decimal
# Round up
# Round down

# Calculate a 15% discount

Round to 1 decimal
[ 13.  46.  10. 101.  55.]

Round up:
[ 13.  46.  10. 101.  56.]

Round Down:
[ 12.  45.   9. 100.  55.]

Calculate a 15% discount
[11.0415 38.675   8.4915 85.6375 47.005 ]


Exercise 3 — Temperatures & Mathematical Functions

This exercise combines some of the functions we just learned.

In [30]:
import numpy as np

temperatures = np.array([-5, -2, 3, -10, 8, 15, -1])

print("Convert every value to positive")
print(np.abs(temperatures))

print("\nFinding square roots:")
import numpy as np
numbers = np.array([4,9,16,25])
print(np.sqrt(numbers))

print("Raise [2,4,6] to the power of 3")
import numpy as np
numbers = np.array([2,4,6])
print(np.power(numbers, 3))
# Convert every value to positive
# Find square roots of [4,9,16,25]
# Raise [2,4,6] to the power of 3

Convert every value to positive
[ 5  2  3 10  8 15  1]

Finding square roots:
[2. 3. 4. 5.]
Raise [2,4,6] to the power of 3
[  8  64 216]


# Importing numpy as np once is enough for the whole coding


🏆 Day 51 — Mini Challenge



In [36]:
import numpy as np

profits = np.array([
    [1200, 1500, 1800],
    [2200, 2400, 2600],
    [900, 1100, 1300]
])

print("Adding 10% to every profit")
increase = profits * 0.10
new_profits = profits + increase
print(new_profits)

print("\nround the result")
print(np.round(new_profits))

print("\nCalculating square root")
print(np.sqrt(new_profits))

print("\nFinding the highest value")
print(np.max(new_profits))
# Task 1 — Add 10% to every profit
# Task 2 — Round the result
# Task 3 — Calculate square root
# Task 4 — Find the highest value

Adding 10% to every profit
[[1320. 1650. 1980.]
 [2420. 2640. 2860.]
 [ 990. 1210. 1430.]]

round the result
[[1320. 1650. 1980.]
 [2420. 2640. 2860.]
 [ 990. 1210. 1430.]]

Calculating square root
[[36.33180425 40.62019202 44.49719092]
 [49.1934955  51.38093031 53.47896783]
 [31.46426545 34.78505426 37.8153408 ]]

Finding the highest value
2860.0
