1. What is np.where()?

You already know how to filter:

sales[sales > 300]

This gives you the values that satisfy the condition.

But np.where() lets you say:

If this condition is true, give me this. Otherwise, give me that.

In [1]:
import numpy as np

sales = np.array([100, 250, 400, 150, 500])

result = np.where(sales > 300, "High", "Low")

print(result)

['Low' 'Low' 'High' 'Low' 'High']


2. np.where() can return positions

If you give it only a condition:

In [2]:
sales = np.array([100, 250, 400, 150, 500])

positions = np.where(sales > 300)

print(positions)

(array([2, 4]),)


3. np.where() with 2D arrays

Let's use our familiar sales dataset:

In [3]:
sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

# Suppose:

# Sales above 300 = "High"
# Everything else = "Low"
result = np.where(sales > 300, "High", "Low")
print(result)

[['Low' 'Low' 'Low' 'Low']
 ['Low' 'Low' 'High' 'High']
 ['High' 'High' 'High' 'High']
 ['Low' 'Low' 'Low' 'Low']]


4. np.where() vs Boolean Filtering

This distinction is important.

In [4]:
sales[sales > 300]

array([320, 350, 500, 450, 470, 520])

In [5]:
np.where(sales > 300, "High", "Low")

array([['Low', 'Low', 'Low', 'Low'],
       ['Low', 'Low', 'High', 'High'],
       ['High', 'High', 'High', 'High'],
       ['Low', 'Low', 'Low', 'Low']], dtype='<U4')

5. Multiple conditions

You can combine conditions.
For example:

Above 300 → "High"
Between 200 and 300 → "Medium"
Below 200 → "Low"

In [6]:
# YOU CAN DO THIS WITH NESTED np.where()

result = np.where(
    sales > 300,
    "High",
    np.where(sales >= 200, "Medium", "Low")
)

print(result)

[['Low' 'Low' 'Low' 'Medium']
 ['Medium' 'Medium' 'High' 'High']
 ['High' 'High' 'High' 'High']
 ['Medium' 'Medium' 'Medium' 'Medium']]


In [25]:
# Day 61 Exercise

import numpy as np

sales = np.array([
    [120, 150, 180, 200],   # Product A
    [300, 280, 320, 350],   # Product B
    [500, 450, 470, 520],   # Product C
    [250, 270, 260, 290]    # Product D
])

print("Task 1")
result = np.where(sales > 300, "High", "Low")
print(result)

print("Task 2")

positions = np.where(sales > 300)
print(positions)

print("\nTask 3")

result = np.where(
    sales > 400,
    "Excellent",
    np.where(sales >= 300, "Good", "Need Improvement")
)
print(result)

print("\nTask 4")
new_result = np.where(sales < 200, sales +20, sales)
print(new_result)

print("\nTask 5")
positions = np.where((sales > 250) & (sales <500))
print(positions)

print("\nTask 6")
new_result = np.where(
    sales >= 400,
    "High",
    np.where(sales >= 250, "Medium", "Low")
  )
print(new_result)

Task 1
[['Low' 'Low' 'Low' 'Low']
 ['Low' 'Low' 'High' 'High']
 ['High' 'High' 'High' 'High']
 ['Low' 'Low' 'Low' 'Low']]
Task 2
(array([1, 1, 2, 2, 2, 2]), array([2, 3, 0, 1, 2, 3]))

Task 3
[['Need Improvement' 'Need Improvement' 'Need Improvement'
  'Need Improvement']
 ['Good' 'Need Improvement' 'Good' 'Good']
 ['Excellent' 'Excellent' 'Excellent' 'Excellent']
 ['Need Improvement' 'Need Improvement' 'Need Improvement'
  'Need Improvement']]

Task 4
[[140 170 200 200]
 [300 280 320 350]
 [500 450 470 520]
 [250 270 260 290]]

Task 5
(array([1, 1, 1, 1, 2, 2, 3, 3, 3]), array([0, 1, 2, 3, 1, 2, 1, 2, 3]))

Task 6
[['Low' 'Low' 'Low' 'Low']
 ['Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'High' 'High' 'High']
 ['Medium' 'Medium' 'Medium' 'Medium']]
