In [ ]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

# AND &

# Find values that are greater than 200 AND less than 400:

result = sales[(sales > 200) & (sales < 400)]

print(result)

# OR |

# Find values that are less than 150 OR greater than 450:
result = sales[(sales < 150) | (sales > 450)]

print(result)

# NOT ~

# Find values that are NOT greater than 300:
result = sales[~(sales > 300)]

print(result)

In [18]:
# Exercises

import numpy as np

sales = np.array([
    [120, 150, 180, 200],   # Product A
    [300, 280, 320, 350],   # Product B
    [500, 450, 470, 520],   # Product C
    [250, 270, 260, 290]    # Product D
])

print("All sales value greater than 200")
result_1 = np.where(sales > 200)
print(result_1)

print("\nTask 2")
result_2 = np.where((sales >= 250) & (sales < 400))
print(result_2)

print("\nTask 3")
result_3 = np.where((sales < 150) | (sales > 450))
print(result_3)

print("\nTask 4")
result_4 = sales[~(sales > 300)]
print(result_4)

print("\nTask 5")
result_5a = np.where((sales >= 250) & (sales < 400))
print(result_5a)
result_5b = sales[(sales >= 250) & (sales < 400)]
print(result_5b)

print("\nTask 6")
result_6 = sales[sales > 250]
new_sales = np.sum(result_6)
print(new_sales)

All sales value greater than 200
(array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))

Task 2
(array([1, 1, 1, 1, 3, 3, 3, 3]), array([0, 1, 2, 3, 0, 1, 2, 3]))

Task 3
(array([0, 2, 2, 2]), array([0, 0, 2, 3]))

Task 4
[120 150 180 200 300 280 250 270 260 290]

Task 5
(array([1, 1, 1, 1, 3, 3, 3, 3]), array([0, 1, 2, 3, 0, 1, 2, 3]))
[300 280 320 350 250 270 260 290]

Task 6
4010
