Day 62 — NumPy Conditional Operations

1. np.where() with one condition
2. np.where() with multiple conditions
3. Nested np.where()
4. Using conditions to create categories
5. Combining np.where() with boolean masks
6. Practical data-analysis exercise

In [1]:
import numpy as np

sales = np.array([100, 250, 400, 150])

result = np.where(sales >= 250, "High", "Low")

print(result)

['Low' 'High' 'High' 'Low']


In [ ]:
# 2️⃣ Multiple categories

result = np.where(
    sales >= 400,
    "High",
    np.where(sales >= 250, "Medium", "Low")
)

print(result)

['Low' 'Medium' 'High' 'Low']


# This gives us:

>= 400 → High
>= 250 → Medium
< 250 → Low

This is very useful in real data analysis.

In [23]:
# Day 62 Exercise

import numpy as np

sales = np.array([
    [120, 150, 180, 200],   # Product A
    [300, 280, 320, 350],   # Product B
    [500, 450, 470, 520],   # Product C
    [250, 270, 260, 290]    # Product D
])

result_1 = np.where(
    sales < 200,
    0,
    sales
)
print(result_1)

print("\nTask 2")

result_2 = np.where(sales >= 400, "High", "Normal")
print(result_2)

print("\nTask 3")
result_3 = np.where(
    sales >= 400,
    "High",
    np.where(sales >= 250, "Medium", "Low")
)
print(result_3)


print("\nTask 4")
high_sales = sales >= 400
result_4 = high_sales.any(axis = 1)
print(result_4)

print("\nTask 5")
result_5 = np.where(sales >= 400,"TOP", "Normal")
print(result_5)

print("\nTask 6")
Final_result = np.where(
    sales >= 400,
    "Excellent",
    np.where(
    sales >= 300,
    "Good",
    np.where(sales >= 200, "Average", "Low"))
)
print(Final_result)


[[  0   0   0 200]
 [300 280 320 350]
 [500 450 470 520]
 [250 270 260 290]]

Task 2
[['Normal' 'Normal' 'Normal' 'Normal']
 ['Normal' 'Normal' 'Normal' 'Normal']
 ['High' 'High' 'High' 'High']
 ['Normal' 'Normal' 'Normal' 'Normal']]

Task 3
[['Low' 'Low' 'Low' 'Low']
 ['Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'High' 'High' 'High']
 ['Medium' 'Medium' 'Medium' 'Medium']]

Task 4
[False False  True False]

Task 5
[['Normal' 'Normal' 'Normal' 'Normal']
 ['Normal' 'Normal' 'Normal' 'Normal']
 ['TOP' 'TOP' 'TOP' 'TOP']
 ['Normal' 'Normal' 'Normal' 'Normal']]

Task 6
[['Low' 'Low' 'Low' 'Average']
 ['Good' 'Average' 'Good' 'Good']
 ['Excellent' 'Excellent' 'Excellent' 'Excellent']
 ['Average' 'Average' 'Average' 'Average']]


In [ ]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200],   # Product A
    [300, 280, 320, 350],   # Product B
    [500, 450, 470, 520],   # Product C
    [250, 270, 260, 290]    # Product D
])

print("Task 1")
first_result = np.where(
    sales < 200,
    0,
    sales
)
print(first_result)

print("Task 2")
second_result = np.where(
    sales >= 400,
    "High",
    np.where(sales > 400, "HIgh", "Normal" )
)
print(second_result)

print("\nTask 3")
third_result = np.where(
    sales >= 400,
    "High",
    np.where(sales >= 250, "Medium", "Low")
)

print(third_result)

print("\nTask 4")


Task 1
[[  0   0   0 200]
 [300 280 320 350]
 [500 450 470 520]
 [250 270 260 290]]
Task 2
[['Normal' 'Normal' 'Normal' 'Normal']
 ['Normal' 'Normal' 'Normal' 'Normal']
 ['High' 'High' 'High' 'High']
 ['Normal' 'Normal' 'Normal' 'Normal']]

Task 3
[['Low' 'Low' 'Low' 'Low']
 ['Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'High' 'High' 'High']
 ['Medium' 'Medium' 'Medium' 'Medium']]
