Day 63: NumPy — Combining Conditions & Real Data Logic

Today’s goals:

Review np.where()
Combine conditions with & and |
Use conditions on 2D arrays
Practice nested np.where()
Build a small sales classification exercise

In [1]:
import numpy as np

sales = np.array([120, 280, 450, 190, 350])

result = np.where(
    sales >= 300,
    "High",
    "Low"
)

print(result)

['Low' 'Low' 'High' 'Low' 'High']


# Multiple conditions

In [2]:
result = np.where(
    sales >= 400,
    "High",
    np.where(
        sales >= 250,
        "Medium",
        "Low"
    )
)

print(result)

['Low' 'Medium' 'High' 'Low' 'Medium']


In [21]:
# Day 63 Exercise
import numpy as np

sales = np.array([
    [120, 150, 180, 200],   # Product A
    [300, 280, 320, 350],   # Product B
    [500, 450, 470, 520],   # Product C
    [250, 270, 260, 290]    # Product D
])

print("Task 1")
result_1 = np.where(sales > 300)
print(result_1)

print("\nTask 2")
result_2 = np.where(
    sales > 300,
    "High",
    "Low"
)
print(result_2)

print("\nTask 3")
result_3 = np.where(
    sales >= 400,
    "High",
    np.where(
        sales >= 250,
        "Medium",
        "Low"
    )
)
print(result_3)

print("\nTask 4")
result_4 = np.where((sales >= 250) & (sales < 400))
print(result_4)

print("\nTask 5")
result_5 = np.where((sales < 150) | (sales > 450))
print(result_5)

print("\nTask 6")
result_6 = np.where(
    sales >= 400,
    "Excellent",
    np.where(
        sales>= 300,
        "Good",
        np.where(sales >= 200, "Average", "Low")
    )
)

print(result_6)

Task 1
(array([1, 1, 2, 2, 2, 2]), array([2, 3, 0, 1, 2, 3]))

Task 2
[['Low' 'Low' 'Low' 'Low']
 ['Low' 'Low' 'High' 'High']
 ['High' 'High' 'High' 'High']
 ['Low' 'Low' 'Low' 'Low']]

Task 3
[['Low' 'Low' 'Low' 'Low']
 ['Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'High' 'High' 'High']
 ['Medium' 'Medium' 'Medium' 'Medium']]

Task 4
(array([1, 1, 1, 1, 3, 3, 3, 3]), array([0, 1, 2, 3, 0, 1, 2, 3]))

Task 5
(array([0, 2, 2, 2]), array([0, 0, 2, 3]))

Task 6
[['Low' 'Low' 'Low' 'Average']
 ['Good' 'Average' 'Good' 'Good']
 ['Excellent' 'Excellent' 'Excellent' 'Excellent']
 ['Average' 'Average' 'Average' 'Average']]
