1. Quick recap: .any(axis=1)
sales > 300

[[False, False, False, False],
 [False, False, True,  True],
 [ True,  True,  True,  True],
 [False, False, False, False]]

(sales > 300).any(axis=1)

means:

For each row, does ANY value satisfy sales > 300?
Result:

[False, True, True, False]

So rows 1 and 2 contain at least one value greater than 300.

2. np.ix_() — selecting rows and columns

Imagine you want:

rows 0 and 2
columns 1 and 3

You could write:

sales[np.ix_([0, 2], [1, 3])]

Result:

[[150, 200],
 [450, 520]]

What does np.ix_() do?

It creates the correct combination of row and column indexes.

Without going too deep into the mechanics yet:

np.ix_([0, 2], [1, 3])

means:

"Take these rows and combine them with these columns."

3. Important comparison
Selecting rows only
sales[[0, 2]]

gives:

[[120 150 180 200]
 [500 450 470 520]]

Selecting columns only
sales[:, [1, 3]]

gives:

[[150 200]
 [280 350]
 [450 520]
 [270 290]]

Selecting specific rows AND columns
sales[np.ix_([0, 2], [1, 3])]

gives:

[[150 200]
 [450 520]]

That's the main reason we use np.ix_().

In [8]:
#Day 60 Exercise
import numpy as np

sales = np.array([
    [120, 150, 180, 200],   # Product A
    [300, 280, 320, 350],   # Product B
    [500, 450, 470, 520],   # Product C
    [250, 270, 260, 290]    # Product D
])

print("Which rows contain at least one value greater than 300")
print((sales > 300).any(axis= 1))

print("\nUsing Boolean result from task 1 print actual rows containing at least one value greater than 300")
high_sales_rows = sales[(sales > 300).any(axis=1)]

print(high_sales_rows)

print("\ntask 3")
print(sales[np.ix_([0,3], [1,2])])

print("\nTask 4")
print(sales[np.ix_([1,2,3], [0,3])])

print("\nTask 5")
Best_sells_rows = sales[(sales > 300).any(axis =1)]
print(Best_sells_rows[:,[0,3]])

print("\n Task 6")
Best_sells_rows = sales[(sales > 300).any(axis=1)]

print(Best_sells_rows[:, [0, 3]])

  

Which rows contain at least one value greater than 300
[False  True  True False]

Using Boolean result from task 1 print actual rows containing at least one value greater than 300
[[300 280 320 350]
 [500 450 470 520]]

task 3
[[150 180]
 [270 260]]

Task 4
[[300 350]
 [500 520]
 [250 290]]

Task 5
[[300 350]
 [500 520]]

 Task 6
[[300 350]
 [500 520]]
