1️⃣ Boolean Indexing — The Core Idea

In [1]:
import numpy as np

sales = np.array([120, 250, 180, 400, 90])

print(sales > 200)

[False  True False  True False]


# Filtering with Multiple Conditions

Suppose:

sales = np.array([120, 250, 180, 400, 90])

We want:

Sales greater than 100 AND less than 300.

Use &:

result = sales[(sales > 100) & (sales < 300)]

print(result)

In [2]:
import numpy as np

result = sales[(sales > 100) & (sales < 300)]
print(result)

[120 250 180]


# Important numpy meaning.

- AND = &
- or = |
- NOT = ~
Suppose we want everything that is NOT greater than 200.

result = sales[~(sales > 200)]

print(result)


In [3]:
result = sales[~(sales > 200)]
print(result)

[120 180  90]


Boolean Indexing with 2D Arrays

Now let's make this more realistic.

In [5]:
sales = np.array([
    [120, 150, 180, 200],
    [300, 200, 320, 350],
    [90, 110, 130, 100]
])

print(sales > 200)

print(sales[sales > 200]) # to filter

[[False False False False]
 [ True False  True  True]
 [False False False False]]
[300 320 350]


np.where() — Finding Positions

This is extremely useful.

In [6]:
sales = np.array([120, 250, 180, 400, 90])

positions = np.where(sales > 200)

print(positions)

(array([1, 3]),)


np.where() Can Also Replace Values

This is very useful in data cleaning.

In [ ]:
sales = np.array([120, 250, 180, 400, 90])

We want:

Any value below 150 should become 150.

In [7]:
result = np.where(sales < 150, 150, sales)
print(result)

[150 250 180 400 150]


# Day 77 — Exercise 1

In [ ]:
import numpy as np

sales = np.array([120, 250, 180, 400, 90, 320, 150, 275])
print("Task 1")

print(sales[sales > 200])

print("\nTask 2")
result = sales[(sales >= 150) & (sales <= 300)]
print(result)

print("\nTask 3")
result = sales[(sales < 150) | (sales > 300)]
print(result)

print("\nTask 4")
result = np.where(sales < 150, 150, sales)
print(result)

print("\nTask 5")
result = sales[sales > 300]
print(result)

print("\nCombine everything as a challenge")
products = np.array([
    "Laptop",
    "Phone",
    "Tablet",
    "Monitor",
    "Keyboard",
    "Mouse",
    "Headset",
    "Camera"
])

sales = np.array([120, 250, 180, 400, 90, 320, 150, 275])

print("\nTask 6")
result_1 = products[sales > 200]
print(result_1)

print("\nTask 7")
result_2 = products[(sales >= 150) & (sales <= 300)]
print(result_2)

print("\nTask 8")
result_3 = products[sales > 350]
print(result_3)

print("\nTask 9")
result_4 = products[~(sales > 200)]
print(result_4)


Task 1
[250 400 320 275]

Task 2
[250 180 150 275]

Task 3
[120 400  90 320]

Task 4
[150 250 180 400 150 320 150 275]

Task 5
[400 320]

Combine everything as a challenge

Task 6
['Phone' 'Monitor' 'Mouse' 'Camera']

Task 7
['Phone' 'Tablet' 'Headset' 'Camera']

Task 8
['Monitor']

Task 9
['Phone' 'Monitor' 'Mouse' 'Camera']
