# 🟦 Day 72 — NumPy Final Practice & Review

In [ ]:

import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [300, 280, 320, 350],
    [500, 450, 470, 520],
    [250, 270, 260, 290]
])

print("Task 1")
result_1 = sales[sales > 300]
print(result_1)

print("\nTask 2")
result_2 = np.where(sales < 250, 0, sales)
print(result_2)

print("\nTask 3")
result_3 = np.select(
    [
        sales < 200,
        sales < 400,
        sales >= 400,
    ],
    [
        "Low",
        "Medium",
        "High"
    ],
    default= "High"
)
print(result_3)

print("\nTask 4")
result_4 = np.any(sales > 400, axis= 0)
print(result_4)

print("\nTask 5")
result_5 = np.all(sales > 200, axis= 1)
print(result_5)

print("\nTask 6")

total_sales = sales.sum()
average_sales = sales.mean()
maximum_sales = sales.max()
minimum_sales = sales.min()
standard_deviation = sales.std()
variance = sales.var()

print("Total sales =", total_sales)
print("Average sales =", average_sales)
print("Maximum sales =", maximum_sales)
print("Minimum sales =", minimum_sales)
print("Standard deviation =", standard_deviation)
print("Variance =", variance)

print("\nTask 7")
clipped = np.clip(sales, 200, 450)
print(clipped)
clipped_average = clipped.mean()
print("Clipped average=", clipped_average)

print("\nTask 8")

product_totals = np.sum(sales, axis=1)

print("Product totals =", product_totals)

highest_total = product_totals.max()

print("Highest total =", highest_total)

highest_product = np.argmax(product_totals)

print("Product with highest sales = Product", highest_product + 1)






Task 1
[320 350 500 450 470 520]

Task 2
[[  0   0   0   0]
 [300 280 320 350]
 [500 450 470 520]
 [250 270 260 290]]

Task 3
[['Low' 'Low' 'Low' 'Medium']
 ['Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'High' 'High' 'High']
 ['Medium' 'Medium' 'Medium' 'Medium']]

Task 4
[ True  True  True  True]

Task 5
[False  True  True  True]

Task 6
Total sales = 4910
Average sales = 306.875
Maximum sales = 520
Minimum sales = 120
Standard deviation = 119.04404384512482
Variance = 14171.484375

Task 7
[[200 200 200 200]
 [300 280 320 350]
 [450 450 450 450]
 [250 270 260 290]]
Clipped average= 307.5

Task 8
Product totals = [ 650 1250 1940 1070]
Highest total = 1940
Product with highest sales = Product 3
