# NumPy: Advanced Array Operations

np.where()
np.select()
np.unique()
np.sort()
np.argsort()
Combining these operations in data-analysis problems

# 1. np.where() — Conditional Logic

You already know how to filter:

In [1]:
import numpy as np

sales = np.array([100, 250, 80, 400, 150])

print(sales[sales > 200])

[250 400]


# But sometimes we don't want to filter the array.

We want to change values based on a condition.

That's where np.where() comes in.

Example

In [2]:
sales = np.array([100, 250, 80, 400, 150])

result = np.where(sales > 200, "High", "Low")

print(result)

['Low' 'High' 'Low' 'High' 'Low']


In [3]:
scores = np.array([45, 72, 88, 51, 39])
result = np.where(scores >= 60, "Pass", "Fail")

print(result)

['Fail' 'Pass' 'Pass' 'Fail' 'Fail']


# 2. np.select() — Multiple Conditions

What if we have more than two categories?

For example:

Sales < 100 → Low
Sales 100–250 → Medium
Sales > 250 → High

We can use np.select().

In [7]:
import numpy as np
sales = np.array([50, 120, 300, 200, 80, 450])

conditions = [
    sales < 100,
    (sales >= 100) & (sales <= 250),
    sales > 250
]

choices = [
    "Low",
    "Medium",
    "High"
]

result = np.select(conditions, choices, default = "Unknown")

print(result)

['Low' 'Medium' 'High' 'Medium' 'Low' 'High']


# 3. np.unique() — Find Unique Values

Suppose we have customer regions:

In [9]:
regions = np.array([
    "North",
    "South",
    "North",
    "East",
    "South",
    "North"
])

print(np.unique(regions))

['East' 'North' 'South']


# It removes duplicates.

Count unique values

You can also get how many times each value appears:

In [10]:
regions = np.array([
    "North",
    "South",
    "North",
    "East",
    "South",
    "North"
])

values, counts = np.unique(regions, return_counts=True)

print(values)
print(counts)

['East' 'North' 'South']
[1 3 2]


# 4. np.sort()

Sort an array:

In [13]:
sales = np.array([400, 100, 250, 80, 300])

print(np.sort(sales))

print("\nFor decending order")
print(np.sort(sales)[:: -1]) # [::-1] means reverse the array

[ 80 100 250 300 400]

For decending order
[400 300 250 100  80]


# 5. np.argsort() — 

This one is especially useful for Data Analytics.

np.sort() gives you the sorted values.

np.argsort() gives you the positions/indexes that would sort the values.

Example:

In [14]:
sales = np.array([400, 100, 250, 80, 300])

print(np.argsort(sales))

[3 1 2 4 0]


# Output:

[3 1 2 4 0]

Why?

Original:

Index:   0    1    2   3    4
Sales:  400  100  250  80  300

Sorted:

80 → index 3
100 → index 1
250 → index 2
300 → index 4
400 → index 0

Therefore:

[3, 1, 2, 4, 0]

Use argsort() to sort another array

This is where it becomes powerful.

In [15]:
import numpy as np
names = np.array([
    "Alice",
    "Bob",
    "Charlie",
    "David",
    "Emma"
])

sales = np.array([
    400,
    100,
    250,
    80,
    300
])

order = np.argsort(sales)

print(names[order])
print(sales[order])

['David' 'Bob' 'Charlie' 'Emma' 'Alice']
[ 80 100 250 300 400]


In [16]:
import numpy as np

products = np.array([
    "Laptop",
    "Phone",
    "Tablet",
    "Monitor",
    "Keyboard",
    "Mouse"
])

sales = np.array([
    120,
    350,
    80,
    220,
    150,
    60
])

In [37]:
print("Task 1")
status = np.where(sales >= 150, "Good", "Low")
print(status)

print("\nTask 2")
conditions = [
    sales < 100,
    sales <= 250,
    sales > 250
]

choices = [
    "Low",
    "Medium",
    "High"
]
result = np.select(conditions, choices, default= "Unknown")
print(result)

print("\nTask 3")
categories = np.array([
    "Electronics",
    "Electronics",
    "Office",
    "Electronics",
    "Office",
    "Office"
])

values, counts = np.unique(categories, return_counts = True )
print(values)
print(counts)

print("\nTask 4")
print(np.sort(sales))

print("\nTask 5")
order = np.argsort(sales)
print(products[order])
print(sales[order])

print("\nBonus challenge")
order = (np.argsort(sales)[:: -1])
print(products[order])
print(sales[order])


Task 1
['Low' 'Good' 'Low' 'Good' 'Good' 'Low']

Task 2
['Medium' 'High' 'Low' 'Medium' 'Medium' 'Low']

Task 3
['Electronics' 'Office']
[3 3]

Task 4
[ 60  80 120 150 220 350]

Task 5
['Mouse' 'Tablet' 'Laptop' 'Keyboard' 'Monitor' 'Phone']
[ 60  80 120 150 220 350]

Bonus challenge
['Phone' 'Monitor' 'Keyboard' 'Laptop' 'Tablet' 'Mouse']
[350 220 150 120  80  60]


# Mini Data Analysis Challenge

In [14]:
import numpy as np

products = np.array([
    "Laptop",
    "Phone",
    "Tablet",
    "Monitor",
    "Keyboard",
    "Mouse",
    "Headphones",
    "Webcam"
])

sales = np.array([
    120,
    350,
    80,
    220,
    150,
    60,
    280,
    95
])

categories = np.array([
    "Computer",
    "Mobile",
    "Computer",
    "Computer",
    "Accessory",
    "Accessory",
    "Accessory",
    "Accessory"
])

print("Task 1")
performance = np.where(sales >= 150, "Good", "Low")
print("Product Performances", performance)

print("\nTask 2")
conditions = [
    sales < 100,
    (sales >= 100) & (sales <= 250),
    sales > 250
]
level = [
    "Low",
    "Medium",
    "High"
]
sales_level = np.select(conditions, level, default= "unknown")
print(sales_level)

print("\nTask 3")
values, counts = np.unique(categories, return_counts = True )
print("unique_categories=", values)
print("category_counts=", counts)

print("\nTask 4")
order = np.argsort(sales)
print(products[order])
print(sales[order])



print("\nTask 5")
order = np.argsort(sales[:: -1][:3])
print(products[order])
print(sales[order])

Task 1
Product Performances ['Low' 'Good' 'Low' 'Good' 'Good' 'Low' 'Good' 'Low']

Task 2
['Medium' 'High' 'Low' 'Medium' 'Medium' 'Low' 'High' 'Low']

Task 3
unique_categories= ['Accessory' 'Computer' 'Mobile']
category_counts= [4 3 1]

Task 4
['Mouse' 'Tablet' 'Webcam' 'Laptop' 'Keyboard' 'Monitor' 'Headphones'
 'Phone']
[ 60  80  95 120 150 220 280 350]

Task 5
['Tablet' 'Laptop' 'Phone']
[ 80 120 350]
